### ISSUE TITLE
"RCTBridgeModule.h" file not found

### ISSUE THREAD

**Issue by chrise86** [rt2zz/react-native-contacts#1]
Created a new app, followed getting started guide from readme (adding linked libraries etc) and keep getting the above message. Any ideas?

Trying to build the project using a local version of this package.

**Comment by rt2zz** [comment]
My mistake, I was confused about how header search paths worked. Should be fixed now (v0.1.4)

**Comment by chrise86** [comment]
Thanks. For some reason I can't get it to build it with a local module. I either get "build failed" - but no errors, or I get the same "RCTBridgeModule.h" file not found error...

**Comment by rt2zz** [comment]
Not sure why... but this time I directly copied the HEADER_SEARCH_PATHS from react-native-camera, maybe it will work now? (v0.1.5)

**Comment by rt2zz** [comment]
@chrise86 let me know if this is working for you. I have multiple reports of it working for others, so I believe this resolved.
