### ISSUE TITLE
Android getAllContacts not working

### ISSUE THREAD

**Issue by niftylettuce** [rt2zz/react-native-contacts#10]
red screen

```
attempt to invoke interface method boolean android.database.Cursor.moveToNext() on a null object reference
```

**Comment by niftylettuce** [comment]
Occured at `getAll ... ContactsManager.java:38`

**Comment by niftylettuce** [comment]
"Read contacts... 2 mins ago... Allowed 9843 times"

Something must really be off!

**Comment by rt2zz** [comment]
yikes x.x

I have no specific timeline for addressing this, but I will post here when and if I am jumping in

**Comment by rt2zz** [comment]
fwiw, if anyone wants to look into this, I think the better approach here is to adapt code from an existing package like cordova contacts plugin: https://github.com/apache/cordova-plugin-contacts/tree/master/src/android

**Comment by niftylettuce** [comment]
@rt2zz I tried patching it, but `getAll` doesn't work.  Not sure if this is due to some change in Lollipop.  I'm not sure really.  I would gladly pay a $50-100+ bounty if someone fixed this.

**Comment by niftylettuce** [comment]
@elliottsj can you help?

**Comment by niftylettuce** [comment]
@drFabio per our chat!

**Comment by niftylettuce** [comment]
Can anyone help here? @rt2zz please re-open  /cc @morenoh149

**Comment by niftylettuce** [comment]
$250 bug bounty

**Comment by morenoh149** [comment]
I'll look into it

**Comment by morenoh149** [comment]
It's definitely working. Try performing all the steps in the setup guide.
![screen shot 2015-12-09 at 8 22 22 pm](https://cloud.githubusercontent.com/assets/587438/11704096/abbc09c4-9eb2-11e5-9696-7539166925c3.png)

**Comment by niftylettuce** [comment]
No it's not

**Comment by niftylettuce** [comment]
Try it with 300 contacts, try to break it like I did and got those cursor
errors

**Comment by morenoh149** [comment]
how do I load >300 contacts into the simulator?

**Comment by niftylettuce** [comment]
@morenoh149 see <https://stackoverflow.com/questions/4835652/how-to-put-contacts-on-the-android-emulator>, I think you use Virtual SDCard.

**Comment by niftylettuce** [comment]
@morenoh149 you can create contacts with the API here <https://stackoverflow.com/questions/4744187/how-to-add-new-contacts-in-android>

**Comment by niftylettuce** [comment]
see <https://github.com/apache/cordova-plugin-contacts/tree/master/src/android>

**Comment by niftylettuce** [comment]
@morenoh149 also see this code here already done <https://github.com/apache/cordova-plugin-contacts/blob/master/src/android/ContactAccessorSdk5.java#L329-L336>

**Comment by morenoh149** [comment]
It'd be really great if you could upload a sample .vcf file with >300 contacts to gist.github.com for me @niftylettuce

**Comment by morenoh149** [comment]
Might be more productive to implement `addContact` to android and see what happens when we add >300 contacts

**Comment by niftylettuce** [comment]
Yeah - maybe try that and then iterate it over 300 with fake names or
something?

**Comment by niftylettuce** [comment]
https://gist.github.com/niftylettuce/6202138b9ab82f9f8368

**Comment by morenoh149** [comment]
I found one with two http://www.phpclasses.org/browse/file/5543.html

**Comment by niftylettuce** [comment]
@morenoh149 Anything I can do to help?  Do you need some of the bug bounty up front?
