### ISSUE TITLE
"Contacts" is undefined

### ISSUE THREAD

**Issue by 8ctopotamus** [rt2zz/react-native-contacts#102]
I followed all of the steps in the readme for Android, but Contacts returns "undefined".

**Comment by npomfret** [comment]
This is usually a linking problem. Check your java code contains the module.

**Comment by 8ctopotamus** [comment]
Haha bit of a noobie with RN here! What exactly does that mean?

**Comment by npomfret** [comment]
So in your java code there will be a class called MainApplication, in it is a method called `getPackages` which contains a line of code that initialises each of the native modules in your project.  By default there's only one line there, the one that initialises react-native.  But if you've "linked" this project correctly you should see a line that looks like `new ReactNativeContacts(),`.

If it's not there, try running

`react-native link`

Then go back to android studio, (wait for gradle to do its stuff) and that line should appear.

**Comment by 8ctopotamus** [comment]
Hey thanks for the direction npomfret! I am still having issues though.

I found the "getPackages" method in my Main_Application_.java (not Main_Activity_.java like it says in the readme of this repo.) and I added the import and "new ReactNativeContacts()" to that file, so my MainApplication.java now reads:

```
@Override
protected List<ReactPackage> getPackages() {
  return Arrays.<ReactPackage>asList(
      new MainReactPackage(),
      new ReactNativeContacts()
  );
}
```

I also tried ```react-native link``` and it says that "react-native-contacts has already been linked".

Contacts is still coming up undefined. :(

Im using react-native v0.35.0 and react-native-contacts v0.5.1

**Comment by npomfret** [comment]
The docs must be out of date, the class that these things were in used to be called MainActivity.

If you start your app in the debugger in android studio and put a break point in the constructor of a class called 'ContactsManager' (hit ctrl/cmd 'n' to go to class and type "ContactsManager") - does the break point get hit when you run in debug mode?  If so then the java side is good, i think, and the problem must lie in the JS code.

**Comment by 8ctopotamus** [comment]
I'll have to try that out and let you know. I've never really used Android Studio, but was debugging remotely in Chrome.

I'll see if I can figure out how to do that and get back to you!

**Comment by 8ctopotamus** [comment]
Still trying to figure out how to run the app in AS, but I also tried downloading/running this example repo https://github.com/morenoh149/react-native-contacts-test.

I was getting the same error as in my original project.

**Comment by 8ctopotamus** [comment]
So it definitely has to do with the version of React Native I was originally using (0.35.0). 

I randomly init a project with RN v0.27.0 and React-Native-Contacts works!

**Comment by wiipsxbox** [comment]
I had the same issue with RN 0.33

**Comment by aaggarwa88** [comment]
I had the same issue with RN 0.33 but got it to work after following this comment:

https://github.com/rt2zz/react-native-contacts/issues/103#issuecomment-254580328

**Comment by morenoh149** [comment]
closing this as a duplicate as #103 has a workaround
