### ISSUE TITLE
Non-named contacts not being returned

### ISSUE THREAD

**Issue by ChrisPikul510** [rt2zz/react-native-contacts#108]
`.getAll` returns an array just fine, but contacts that do not have a name (given/family) are not present in the results. I created contacts in the simulator containing only email addresses or phone numbers and they are not being returned.

```
Contacts.getAll((err, contacts) => {
   if(err)
      console.error(err)
   else
      console.log(contacts)
})
```

> Platform: iOS
> RN: 0.35.0
> React: 15.3.1
> react-native-contacts: 0.4.1

**Comment by vzhen** [comment]
Platform: Android
RN: 0.38.0
React: 15.4.0-rc.4
react-native-contacts: 0.7.0

my console.log returned as this and only phone numbers and label are return in phoneNumbers.
![capture](https://cloud.githubusercontent.com/assets/1941395/21396263/9236b272-c7da-11e6-9670-975f1655f38e.PNG)

**Comment by npomfret** [comment]
Thanks for the feedback - looks like we introduced a bug in the last release.  I'll try to look at it today.  In the mean time please use the previous version.

**Comment by npomfret** [comment]
Are you seeing this issue on Android, iOS or both?

**Comment by vzhen** [comment]
No chance to test on iOS. I don't have a mac. Yes this issue on Android

**Comment by vzhen** [comment]
Any update?
Is android version fix?

**Comment by npomfret** [comment]
@vzhen see https://github.com/rt2zz/react-native-contacts/issues/87 and try my branch

**Comment by ignivarahulsaini** [comment]
see #144 @ChrisPikul510

**Comment by ChrisPikul510** [comment]
Haven't been able to test the master. Is this up to npm yet with a version, or only available in repo?

**Comment by morenoh149** [comment]
@ChrisPikul510 try @npomfret 's repo. Add the repo name directly into your package.json https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by ChrisPikul510** [comment]
The problem is, my project isn't exactly new or small. So I don't want to switch to a fork if I don't have to (because forks come with their own problems from time to time)

**Comment by morenoh149** [comment]
you either want to test the fork or you don't. Work in a git feature branch. It's the price to pay when using software undergoing development.

The intent is to get a fix published into npm once it's ready. You can wait for that by checking the npm page for updates https://www.npmjs.com/package/react-native-contacts

**Comment by npomfret** [comment]
Your project size isn't exactly relevant.  To change the version your testing (so you can test the code in master) is just the case of changing one line in your package.json.  You don't need to deploy it to production, just build you app and test it.  If the change isn't to you liking simply revert the change, no?

**Comment by ChrisPikul510** [comment]
Yes I know. I'm just currently working on another big feature at the moment, when I get back to the contacts I'll try out the repo and report back. Until then you can mark this as closed if you want.

**Comment by npomfret** [comment]
Can we close this, I think its working now?
