### ISSUE TITLE
Bug bounty for Android support

### ISSUE THREAD

**Issue by niftylettuce** [rt2zz/react-native-contacts#11]
It looks like Android is broken -- see #10 

Could possibly be due to a large # of contacts

**Comment by tUrG0n** [comment]
I had the same problem as you @niftylettuce basically, not being able to load my 1,700+ contacts.
The solution was to catch for null cursors. 
Right now, it works for me and i can fetch all the contacts.
I think the problem is due to some contacts not being actually contacts (skype, fb, etc.. contacts)  because after I fixed the bug, I was basically getting many empty contacts (no name, email phone etc..)

Gonna submit a pull request.
Bounty still on? ^^

**Comment by morenoh149** [comment]
@tUrG0n mind reviewing this pr instead? https://github.com/rt2zz/react-native-contacts/pull/21

**Comment by tUrG0n** [comment]
wow @morenoh149  this kicks ass. Not only does it seam to solve the problem, but its also super fast! 
Lemme do so more testing then i'll confirm, but huge kudos so far :)

**Comment by tUrG0n** [comment]
Ok so first comment @morenoh149 
This method return in my case 409 contacts.
However, If i export the contacts in the default contacts app, it says i got 1931.
Which contacts are not getting imported in ur code?

**Comment by morenoh149** [comment]
The ones omitted are ones that are [invisible](https://developer.android.com/reference/android/provider/ContactsContract.ContactsColumns.html#IN_VISIBLE_GROUP) aka emails from gmail, whatsapp, viber. For this module we are really interested in contacts you'd see in ones addressbook.

If you could double check if it's possible to get the first and last names somehow I'd really appreciate it. No matter what I tried I could only get displayName on my android phone.

**Comment by tUrG0n** [comment]
@morenoh149 awesome stuff man. Yeah I dunno how to get those, but it would be nice to have somwehere in the docs saying that they are set to `''` by default.

As for the contacts, it makes sense.
Is there any way though that I could fetch ALL contacts? Maybe a boolean that I can pass to the method that would do this?

**Comment by morenoh149** [comment]
@rt2zz would have to weigh in on optionally returning invisible contacts (aka emails).

I'll document the '' middle and last names.

**Comment by tUrG0n** [comment]
@morenoh149 so are the invisible contacts ommited in the code? or the code simply doesn't query them?  (I'm trying to hack the code to return them haha)

**Comment by tUrG0n** [comment]
@morenoh149 that does the job ^^ There's still around 200 contacts missing though haha (total = 1931, current retrived = 1752) :P

**Comment by morenoh149** [comment]
only thing I could imagine is those 200 aren't in the [Contactables table](http://developer.android.com/reference/android/provider/ContactsContract.CommonDataKinds.Contactables.html). They may be in https://developer.android.com/reference/android/provider/ContactsContract.html or you are double counting some contacts that span multiple rows (a contact is an aggregation of rows).

**Comment by niftylettuce** [comment]
@morenoh149 Can you fix this?

![screen shot 2016-01-03 at 8 31 27 pm](https://cloud.githubusercontent.com/assets/523141/12082021/12949dbe-b259-11e5-9747-0d191fdf52d9.png)

**Comment by niftylettuce** [comment]
@morenoh149 Basically if you don't have ANY contacts on the phone (e.g. running in emulator)
