### ISSUE TITLE
Readme confusing regarding Android MainActivity edit

### ISSUE THREAD

**Issue by aaroncraigongithub** [rt2zz/react-native-contacts#110]
Currently, the README says to open `android/app/src/main/java/[your-app-namespace]/MainActivity.java`, however, in my project (react-native-cli: 1.0.0, react-native: 0.37.0), that file does not contain the `getPackages` method I'm supposed to edit.

The method does exist in `MainApplication.java` in the same location.

I'm happy to make a PR to update the docs, just want to make sure I'm not missing something first.

**Comment by morenoh149** [comment]
@aaroncraigongithub please do! RN has shuffled things around and the instructions have become outdated.

**Comment by aaroncraigongithub** [comment]
Done (#111)
