### ISSUE TITLE
Android M+ crashes due to permissions changes in Android OS

### ISSUE THREAD

**Issue by theseansy** [rt2zz/react-native-contacts#115]
(You might already be aware of this, but I couldn't find an open issue regarding this, and didn't see implementation for Android M, as far as I could tell)

When I run on an Android M or N device, the app crashes because you have to request permissions at time of use.  Crash logs:
```
java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2
from ProcessRecord{2436583 22723:com.me.myapp/u0a245} (pid=22723, uid=10245)
requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
```
[Stackoverflow post on this](http://stackoverflow.com/questions/29915919/permission-denial-opening-provider-com-android-providers-contacts-contactsprovi).

I'm open to trying to fix this and opening a PR, but just wanted to make sure this wasn't already being addressed.

**Comment by theseansy** [comment]
Ah after some search, assume we should maybe [use this](https://github.com/lucasferreira/react-native-android-permissions) for Android M and N?

**Comment by morenoh149** [comment]
This is the first I've heard of that module. If it solves the problem it should be added to the readme.

**Comment by theseansy** [comment]
@morenoh149 - it solved the problem for me (I just need to read contacts). Will add what I did to the `readme` in a PR

**Comment by fabriziomoscon** [comment]
related: https://github.com/rt2zz/react-native-contacts/issues/83

**Comment by fabriziomoscon** [comment]
@theseansy just a question:
Isn't that library deprecated - as the author suggests?
since RN 0.33 implement the related JavaScript bindings
https://github.com/facebook/react-native/releases/tag/v0.33.0

**Comment by theseansy** [comment]
@fabriziomoscon - Yes, `import {PermissionsAndroid} from 'react-native'` works for this case very nicely for this case.  My mistake is that it says 'FUTURE DEPRECATION WARNING' in the README, which led me to believe `PermissionsAndroid` still wasn't out yet, but would be soon.

**Comment by morenoh149** [comment]
I think this is safe to close then :)

**Comment by eneskaya** [comment]
This should really be mentioned in the docs.

**Comment by morenoh149** [comment]
feel free to submit a PR
