### ISSUE TITLE
Question: If and when to submit pull request

### ISSUE THREAD

**Issue by Proberts** [rt2zz/react-native-contacts#116]
I've forked the repo and will be significantly expanding the number of contact data fields supported. I'm doing Android first, then will do iOS after the Android app releases. I'd like to contribute my additions back to this repo.

Considering my changes will create a difference in iOS and Android behavior (unsupported native fields will be ignored for each platform), should I keep my version separate or is that platform disparity acceptable?

If the disparity is acceptable, should I wait until I have both Android and iOS backends complete before submitting the pull request, or can I submit a PR when Android is complete and indicate in the docs what is and isn't supported yet for iOS?  (I'm new to GitHub and RN. )

**Comment by morenoh149** [comment]
I believe this module intended to provide a uniform (intersection) of contact data available.

Do you intend to build a version that is the union of contact data?

I think each approach has pros and cons:

# union
## pros
* all data available is surfaced to programmer
* features may be added to either platform
## cons
* the application must perform checks for existence (or absence) of contact fields

# intersect
## pros
* uniform api between ios and Android
## cons
* obviously some data on the device would not be made available
* features can only be added if equivalent code is contributed for both platforms.
  * slows down development

**Comment by Proberts** [comment]
I'm hoping all the fields I need supported are an intersection, but I wouldn't be surprised if it ends up being a union at some level. I'm working with normal contact data, but I can see how some of the mappings when creating a contact wouldn't naturally be bidirectional. For example, when creating a contact, some field types on Android may map to specific entities like TYPE_NAME_PETS and TYPE_NAME_SPOUSE but both map to TYPE_NAME_OTHER on iOS, or vice-versa.  I hadn't considered what a query of the phone's contacts database would return in this case. I only need to create and update contacts, not read them back in, so unidirectional coherence works fine in my case. 

Would it be reasonable to create the API so that all fields passed for creating and updating contacts would not be guaranteed to be bidirectional? If the docs indicate which fields are guaranteed to be bidirectional, the developer could choose to use or not use the unidirectional fields.

**Comment by Proberts** [comment]
If you want to take a look [here](https://github.com/Proberts/react-native-contacts/tree/contact-expansion), I've updated the docs in my fork with what I've added or am adding.

**Comment by morenoh149** [comment]
Seems like you are serious about extending the project. I think a table denoting what features are available on what platform (as you've done) is excellent. Let's go with the Union and good documentation.

**Comment by Proberts** [comment]
I've updated the docs to reflect the scope of what I need to add for my app. I'm happy for suggestions or comments.

The Android work is just about done. Should I submit a pull request once it's done?  The iOS version should be brought up to date with the Android version in the next two weeks. Should I wait both iOS and Android are complete?

**Comment by npomfret** [comment]
I think in this project it's best to have feature parity.

**Comment by Proberts** [comment]
I think iOS and Android look like they'll have the same set of details. So far I haven't found anything I added to Android that I can't add to iOS. Phonetic name is a little different but is bidirectional with a caveat.

The only set of details that looks like it may be significantly different between platforms is social media accounts. Android doesn't support them at all, but they might be able to be added as special fields. They won't show up in the phone's contact manager, but will be there if read by RN or by an external contacts manager.
