### ISSUE TITLE
Partial contacts (email address only) are not returned

### ISSUE THREAD

**Issue by krishangupta** [rt2zz/react-native-contacts#121]
If I make a contact with only an email address (and no familyName or givenName), it will not be returned by `Contacts.getAll`. 

I've tested on the simulator only so far. Returning a contact, even if just for the email address would be super useful for invite screens.

Thanks!

**Comment by npomfret** [comment]
Is this on Android or iOS?

**Comment by krishangupta** [comment]
@npomfret ios

**Comment by npomfret** [comment]
Can we close this, I believe its fixed.
