### ISSUE TITLE
Performance bug in Android getAll()

### ISSUE THREAD

**Issue by Proberts** [rt2zz/react-native-contacts#124]
There's a bug (?) in ContactsProvider.java where each piece of information in a contact record results in getPhotoURIFromContactURI() being called - i.e. If a contact has 1 name, 2 phone numbers and 2 email addresses, getPhotoURIFromContactURI() will be called 5 times for the same contact.  Multiple calls per contact only result in 1 file in the cache, but for each call the image is re-copied. (I've fixed this in my fork, and will submit a pull req, but thought this was important enough to post here now.) 

ContactsProvider.java :

`
155:            if (!TextUtils.isEmpty(rawPhotoURI)) {
`

should read

`
155:             if (!TextUtils.isEmpty(rawPhotoURI) && TextUtils.isEmpty(contact.photoUri)) {
`

**Comment by npomfret** [comment]
Hi. Thanks for looking at this. I can take a look at the code tomorrow. Unless you feel like submitting a PR?

**Comment by npomfret** [comment]
https://github.com/rt2zz/react-native-contacts/pull/126

@morenoh149 this is a good one-liner.  would you like to review and push if it looks ok?

**Comment by morenoh149** [comment]
@npomfret looks like your one liner was in master already.

**Comment by bourgois** [comment]
Great :) Could someone push a new release? We are still at 0.2.2...

**Comment by morenoh149** [comment]
done

**Comment by npomfret** [comment]
Yes, sorry I should have close this.  It was included in the other performance fix I merged
