### ISSUE TITLE
Contacts.PERMISSION_AUTHORIZED and other const values null on Android

### ISSUE THREAD

**Issue by SRandazzo** [rt2zz/react-native-contacts#131]
On iOS, referencing:
```
Contacts.PERMISSION_AUTHORIZED || Contacts.PERMISSION_UNDEFINED || Contacts.PERMISSION_DENIED
```
yields `authorized`, `undefined`, and `denied` respectively. 

On Android, these values are all null

Is this intentional behavior or a bug?

Thanks!

**Comment by eneskaya** [comment]
Facing the same issue

**Comment by mattdwardle** [comment]
@eneskaya what do you mean wants to use PermissionsAndroid? I am experiencing the same issue.

**Comment by morenoh149** [comment]
the recommended installation now uses PermissionsAndroid. Readme updated.
