### ISSUE TITLE
get contacts by phone number.

### ISSUE THREAD

**Issue by GeekRishabh** [rt2zz/react-native-contacts#137]
### How to search the data rather complete info saved in address book if we have phone number .

eg> i want to search records having mobile number '0000000000'

ie. if Contacts.phoneNumbers[i].number=0000000000
where i can be any integer depending on the number of phoneNumbers saved.

and i need to get other details rather complete json data related to the above number .

like name ,email etc

**Comment by morenoh149** [comment]
use a for loop

**Comment by hatemalimam** [comment]
What's the status of this ? any plans on supporting it ?

**Comment by morenoh149** [comment]
Open to adding it. Submit a PR @hatemalimam

**Comment by hatemalimam** [comment]
@morenoh149 please consider to close this issue.

**Comment by morenoh149** [comment]
yep. In future you can use keywords in PRs to close related issues https://help.github.com/en/articles/closing-issues-using-keywords
