### ISSUE TITLE
Refactoring and details added to contacts fetched in iOS

### ISSUE THREAD

**Issue by JeanLebrument** [rt2zz/react-native-contacts#14]
Hello,

The code is ready on the branch `moreInfosFromUser` of my fork: https://github.com/JeanLebrument/react-native-contacts/tree/feature/moreInfosFromUser

I created a category `APContact+EasyMapping` to map `APContact` that I included in the project: https://github.com/JeanLebrument/APContact-EasyMapping

However, I have some breaking changes with the current JSON provided by your library. 

The representation of `APContact` in `NSDictionary` is strictly identical to the model. (For the thumbnail, I serialized the `UIImage` in Base 64 `String`).

I could modify the JSON outputted by the iOS Native Module in the Javascript to modify its representation to keep the actual one of your package but here are my observations:
- With APAddressBook I can't retrieve the URL of the image but I can get the the UIImage then serialize it in Base 64. I can use the Base 64 representation of the image in the `Image` component.
- I like the representation proposed by `APAddressBook`. I think its cleaner especially with the growing amount of data fetched for each user. What do you think?

**Comment by rt2zz** [comment]
I have not fully looked through it yet, but a few initial thoughts:

I like the direction here. Code is much cleaner!

I understand the decision to go with base64 images vs the copy image hack. I am ok with this change but I believe we should not return images by default, instead add an option to load images.

**Comment by JeanLebrument** [comment]
I agree with your last point. There is no limitation either with APAddresBook, we can select the fields we wan't to retrieve with a white list.

**Comment by JeanLebrument** [comment]
I gonna update my pool request as soon as I can.

**Comment by rt2zz** [comment]
One more thought: Can we translate firstName / lastName to givenName / familyName. As this is the w3c standard, and moreover Contacts api (ios9+) and android use this scheme as well.

I am tied up for the next week, but will review any PR's, plus you have commit acces :)

**Comment by morenoh149** [comment]
Submit a PR when the changes are ready.
