### ISSUE TITLE
contacts with no name are not fetched by package.

### ISSUE THREAD

**Issue by imbudhiraja** [rt2zz/react-native-contacts#144]
I'm trying to fetch all device contacts but contacts with no name are not fetched.
```js
Contacts.getAll((err, contacts) => {
        if(err){
          if(err.type === 'permissionDenied'){
            alert('Please go to Settings > Privacy > Contacts to allow "xyz" to access your Contacts');  
          }
          else{
            alert(err);  
          }
        } else {
          context.getcontact();
        }
      })
```
Platform : iOS,
React-Native - 0.24.

Thanks

**Comment by morenoh149** [comment]
please use triple backticks (```) around code snippets

**Comment by npomfret** [comment]
Please test on master - I believe this is fixed.

**Comment by imbudhiraja** [comment]
@npomfret  same issue with updated version.

**Comment by imbudhiraja** [comment]
@morenoh149 i tried with triple backticks (```). but same result can you plz share the sample code.

**Comment by imbudhiraja** [comment]
Resolve this by commenting following code in  RCTContact.m

if(!hasName){
    //nameless contact, do not include in results
    //return nil;
  }

Thanks

**Comment by npomfret** [comment]
That code is not on master, it's been removed.  Please check again.  Change your package.json to point to master rather than the released version

**Comment by imbudhiraja** [comment]
Thanks a lot.
