### ISSUE TITLE
Cannot read property 'checkPermission' of undefined

### ISSUE THREAD

**Issue by AdrianZghibarta** [rt2zz/react-native-contacts#147]
When I am trying to use the library on Android, the imported Contacts (import Contacts from "react-native-contacts";) is undefined. What I am doing wrong ?

**Comment by npomfret** [comment]
This is usually a _linking_ problem.

**Comment by AdrianZghibarta** [comment]
Yes, thanks for info. I've opened the Android app in Android Studio and the gradle sync fixed that.

**Comment by wzup** [comment]
This is NOT a linking problem!

I have linked the lib but I still have this problem
```
$ react-native link react-native-contacts
Scanning folders for symlinks in /Users/user/app/node_modules (42ms)
rnpm-install info Platform 'ios' module react-native-contacts is already linked 
rnpm-install info Platform 'android' module react-native-contacts is already linked 
rnpm-install info Linking assets to ios project 
rnpm-install info Linking assets to android project 
rnpm-install info Assets have been successfully linked to your project
```

**Comment by felipesousa** [comment]
do you can try add IOS mannually, it's fix the error.
https://github.com/rt2zz/react-native-contacts#manual
