### ISSUE TITLE
getAll never return on iOS if permission is denied

### ISSUE THREAD

**Issue by bourgois** [rt2zz/react-native-contacts#151]
On iOS 10.2.1 (didn't test on other version), if we use the
```
Contacts.getAll((err, contacts) => {
  if(err && err.type === 'permissionDenied'){
    // x.x
  } else {
    console.log(contacts)
  }
})
```
We in fact never exit the getAll call and never trigger the err.type='permissionDenied'

We didn't test that properly in previous versions, so I don't know if this is a regression or an old issue...

*EDIT: use triple back ticks for code regions `*

**Comment by npomfret** [comment]
Thanks for the info, I also don't know if it's a regression.  This would be a good thing to submit as a first PR if you know how.

**Comment by brianomchugh** [comment]
I am having an issue where getAll (and getAllWithoutPhotos) never returns, regardless of the permissions set. This is happening only on certain devices so far: 4s running IOS 8.1 and 6 running IOS 10.2.1. Here is the code  I am using to check:
```
 Contacts.checkPermission((err, permission) => {
   console.log(permission) // prints 'authorized'
   console.log("about to get contacts")
   Contacts.getAllWithoutPhotos((err, contacts) => {
     console.log("made it")  // never prints
   })
 })
```

**Comment by npomfret** [comment]
Yes, apparently apple reported close to 100% conversion to iOS 9 or above, so we stopped supporting 8 and moved to the new contacts api.  It seems much faster and more stable now.

**Comment by npomfret** [comment]
Are you able to test https://github.com/rt2zz/react-native-contacts/pull/157 - it has some improvements around the permissions handling.

**Comment by npomfret** [comment]
@brianomchugh @bourgois  Are you able to test #157 - it has some improvements around the permissions handling.

**Comment by npomfret** [comment]
Can we close this?

**Comment by bourgois** [comment]
Yes! Thanks @npomfret
