### ISSUE TITLE
getAll on Android causes app to crash

### ISSUE THREAD

**Issue by gp3gp3gp3** [rt2zz/react-native-contacts#152]
Hello,

I'm having an issue using this library with Android.  On iOS in the simulator I can get permissions working and get access to the contacts in the phone.  But when I install the app on my Pixel XL, if I use the read permissions block of code, my permissions come back 'denied' immediately.  If I then try using `getAll` instead of `checkPermissions / readPermissions`, the app just crashes.  Any idea what's happening?

```
package.json

  "dependencies": {
    "axios": "^0.15.3",
    "lodash": "^4.17.2",
    "moment": "^2.17.1",
    "react": "15.4.1",
    "react-native": "0.40.0",
    "react-native-code-push": "^1.16.1-beta",
    "react-native-contacts": "^0.7.1",
    "react-native-emoji": "^1.2.0",
    "react-native-fbsdk": "^0.5.0",
    "react-native-router-flux": "^3.37.0",
    "react-native-snackbar": "^0.3.1",
    "react-native-vector-icons": "4.0.0",
    "react-redux": "^5.0.1",
    "redux": "^3.6.0",
    "redux-thunk": "^2.1.0"
  },
  "devDependencies": {
    "babel-jest": "18.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "18.0.0",
    "react-test-renderer": "15.4.1"
  },
```

Let me know what other info you need.  Thanks!

**Comment by morenoh149** [comment]
there was just a new release of this package supporting RN 0.40. Please give that a shot and report back.

**Comment by gp3gp3gp3** [comment]
@morenoh149 Unfortunately it seems to still be doing the same behavior, respective to each function call.  `denied` for permissions and immediate crashes for `getAll()`

**Comment by daohenry** [comment]
I got the same issue. It worked after I added 
<uses-permission android:name="android.permission.READ_PROFILE" />
to AndroidManifest.xml

**Comment by morenoh149** [comment]
@gp3gp3gp3 @daohenry were those instructions not in the readme? https://github.com/rt2zz/react-native-contacts#android could they be more clear or obvious?

**Comment by daohenry** [comment]
hey @morenoh149, I only need to read the contacts so I only added 
`<uses-permission android:name="android.permission.READ_CONTACTS" />`
Change 
 `<uses-permission android:name="android.permission.READ_PROFILE" />` to be compulsory maybe?

**Comment by morenoh149** [comment]
oh, is "reading contacts" dependent on `READ_CONTACTS` and `READ_PROFILE`?

**Comment by daohenry** [comment]
yeah, I guess. The app crashed when getAll is called without  `READ_PROFILE`

**Comment by gp3gp3gp3** [comment]
I didn't add _anything_ in my AndroidManifest.xml because for some reason while skimming the readme file, I saw the `below RN version 0.21.0` line and assumed the instructions below only were related to that.

Sorry about that, just me being dumb for not reading the whole readme entirely!

**Comment by navneet-kumar** [comment]
Read this : https://github.com/rt2zz/react-native-contacts/issues/218
