### ISSUE TITLE
Value for contact usage info.plist is not optional for deployment [iOS]

### ISSUE THREAD

**Issue by gp3gp3gp3** [rt2zz/react-native-contacts#153]
Hello again!

I just wanted to let you know that while the value for that contact usage is optional for development builds, the apple store will reject it upon deployment unless you include a description of why you need the contact info as a string value.  Might be worthwhile to include in the readme to save people a rebuild when deploying their app.

Thanks for the library!

**Comment by RUIFERNANDE5** [comment]
Thanks god, you saved my life.
After uploading it to itunes connect and build disappearing after pending status.
However I had no access to the itunes email so I couldn't read possible errors.

Should be added on the docs.
