### ISSUE TITLE
How to open contacts app when adding a contact?

### ISSUE THREAD

**Issue by hecontreraso** [rt2zz/react-native-contacts#155]
Hello guys! I want to save a contact. I don't want to save it 'directly' to the address book, but to open the contacts app, filling the form fields with the sent data. How can I do this? And if is not possible with this library, do you know any other option?

Look at this image: https://i.stack.imgur.com/2ryDu.png

Any help will be greatly appreciated!

**Comment by morenoh149** [comment]
I don't think this library does this. Instead you'd want to launch the native contacts app. In android I think you'd use an intention. I'd search through android studio's samples and skim https://developer.android.com/reference/android/content/Intent.html#CATEGORY_APP_CONTACTS This vid is a good overview https://www.youtube.com/watch?v=95AARxHoupA I'd also check https://developer.android.com/guide/components/intents-filters.html#ExampleExplicit

and lesson 3 of https://www.udacity.com/course/new-android-fundamentals--ud851

feel free to ping here if you think the issue should remain open
