### ISSUE TITLE
Is there any identifier to recognize that a particular contact is already present?

### ISSUE THREAD

**Issue by bietkul** [rt2zz/react-native-contacts#159]
We have recordId but it changes (depends on device), I want to check whether a contact is present or not before updating it,

**Comment by morenoh149** [comment]
the recordId should be static on a single device. If you want to test if two contacts are the same across devices, you'll have to perform a similarity check. Look into elasticsearch or the [ILIKE](http://devdocs.io/postgresql~9.5/functions-matching#FUNCTIONS-LIKE) operator in databases.
