### ISSUE TITLE
feature request: js notification when the address book changes

### ISSUE THREAD

**Issue by npomfret** [rt2zz/react-native-contacts#162]
(note to self!)

**Comment by pewh** [comment]
hello,

is there any roadmap for detect if contact has been changed? I need this feature for my chatting app, which auto refresh contact if any change happened.

It's not efficient to trigger `getAll` every background->foreground state.

Thanks.

**Comment by morenoh149** [comment]
@pewh no roadmap. Feel free to submit a PR.

**Comment by morenoh149** [comment]
dupe https://github.com/rt2zz/react-native-contacts/issues/57
