### ISSUE TITLE
suggestion: move to promises

### ISSUE THREAD

**Issue by npomfret** [rt2zz/react-native-contacts#165]
Would it make sense to move the api to use promises rather than callbacks?  I'm not exactly sure when people tend to use one over the other, possibly when there are some background tasks involved in the native code.  Which I believe we do have in here.

**Comment by morenoh149** [comment]
I think promises are pretty popular. There are some js folks I know that still prefer callbacks. Is it hard to support both?

**Comment by npomfret** [comment]
I'm sure you could support both, but I think it might lead to confusion.

I've started using the async / await syntax in my RN apps which makes using promises a lot nicer, not so much nasty boilerplate code.  And neater than callbacks too.

**Comment by pewh** [comment]
Any progress about promise?

**Comment by thomazfeitoza** [comment]
I did some tests modifying the project in my own node_modules directory and it ran nice on android. In my opinion promises are cleaner especially when using async/await. +1 to support to promises.

**Comment by yqbk** [comment]
My solution in the case anybody needs promises for _redux-saga_ or some other async code:


```JavaScript
function getContacts() {
    return new Promise(resolve => {
        Contacts.getAll((error, contacts) => {
            if (error) {
                throw error;
            } else {
                resolve(contacts);
            }
        });
    });
}
```

**Comment by jacob-israel-turner** [comment]
If the collaborators are ok with it, I may take a whack at promisifying the library.  I will ensure that callbacks are supported as well, for backwards compatibility.

**Comment by morenoh149** [comment]
@jacob-israel-turner absolutely, please submit a PR :)

**Comment by morenoh149** [comment]
dupe https://github.com/rt2zz/react-native-contacts/issues/17

**Comment by Bilal-Abdeen** [comment]
To use this great component with Redux, I needed to make it return promises (rather than callbacks). Using the hints in this thread and other resources, I came up with a solution for calling this component from a Redux's Action (Action Creator). 

Please, refer to the following question on StackOverflow. 
https://stackoverflow.com/questions/58126240/in-a-reduxs-action-calling-a-function-with-callbacks

**Comment by hengkx** [comment]
any progress?
