### ISSUE TITLE
Add a method to filter contacts in Objective-C/Java and return results.

### ISSUE THREAD

**Issue by diatrevolo** [rt2zz/react-native-contacts#167]
Returning all contacts to ReactNative can be a slow process, especially when a user has hundreds or thousands of contacts. I propose implementing an API on the native side to get parameters from React, get a subset of contacts, and return only the relevant results back to React.

**Comment by diatrevolo** [comment]
I have already begun work on the Objective-C implementation, and am happy to take on the Java work as well.

**Comment by morenoh149** [comment]
this sounds good. Could you propose a function signature for how this would work from the javascript side.

**Comment by diatrevolo** [comment]
Thanks!. I was thinking along the lines of
```
Contacts.getContactsMatchingString(string, (err, contacts) => {
  if(err === 'denied'){
    // x.x
  } else {
    console.log(contacts)
  }
})
```
in order to match getAll as closely as possible. Please let me know if there is a better signature that would be more adequate.

**Comment by diatrevolo** [comment]
Addressed by https://github.com/rt2zz/react-native-contacts/pull/170
