### ISSUE TITLE
Cannot install using npm install command

### ISSUE THREAD

**Issue by tsmrafee-bs** [rt2zz/react-native-contacts#177]
When i run the command `npm install react-native-contacts` it gives me the following error

![image](https://cloud.githubusercontent.com/assets/27723951/26389771/608c32a8-407d-11e7-8062-4695a35dad64.png)

How can i install it?

**Comment by npomfret** [comment]
Not sure what's going on here!  Have you tried deleting your node_modules and trying again?

**Comment by morenoh149** [comment]
I see windows

**Comment by tsmrafee-bs** [comment]
@npomfret, yeah I tried this...but same result

**Comment by npomfret** [comment]
No idea, sorry.  Have you tried:

 * npm cache clean
 * run as administrator
 * upgrade npm
 * web search for "windows npm EPERM"!?
