### ISSUE TITLE
suggestion: update readme to just use "react-native link"

### ISSUE THREAD

**Issue by raould** [rt2zz/react-native-contacts#178]
If it is ok to just use react-native link, that would be less scary / preferable I suspect?

**Comment by morenoh149** [comment]
never used it. Submit a PR.

**Comment by npomfret** [comment]
@raould agreed - i only use `react-native link` now, seem to be reliable enough.

**Comment by npomfret** [comment]
https://github.com/rt2zz/react-native-contacts/pull/179
