### ISSUE TITLE
null object reference

### ISSUE THREAD

**Issue by morenoh149** [rt2zz/react-native-contacts#18]
repeatedly calling `getContacts` in an app sometimes causes  the following error
```
  attempt to invoke interface method 'boolean android.database.Cursor.moveToNext()' on a null object reference
```
![screen shot 2015-12-15 at 8 01 10 pm](https://cloud.githubusercontent.com/assets/587438/11828942/dc4b7eb8-a366-11e5-93e2-46a65e1f39fa.png)

**Comment by morenoh149** [comment]
does `eCur` have to be guarded against null case as well? https://github.com/rt2zz/react-native-contacts/blob/master/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java#L91

**Comment by rt2zz** [comment]
I think this was fixed in https://github.com/rt2zz/react-native-contacts/pull/13 and I simply need to cut a new release

**Comment by rt2zz** [comment]
ah yes, you are right, I think eCur needs the same null check

**Comment by morenoh149** [comment]
I'm currently rewriting the logic. PR soon.
