### ISSUE TITLE
missing/no thumbnails showing on Android

### ISSUE THREAD

**Issue by raould** [rt2zz/react-native-contacts#182]
(Dunno about iOS since the contacts in the Simulator don't seem to come with pictures.)

I used https://github.com/milosmns/contacts-generator-android to set up a ton of contacts on Android. When I use react-native-contacts I get all the info except that the thumbnails are always false/empty. Whereas when I use https://github.com/robdodson/contacts-app on the same emulator then it appears to be getting thumbnails since I see little thumbnails in that app.

"react-native": "0.44.0",
"react-native-contacts": "^0.8.1
Android emulator running 4.4
(i guess see also: https://github.com/rt2zz/react-native-contacts/pull/64)

**Comment by npomfret** [comment]
Have you tried using `getAllWithoutPhotos` or `getAll`?  I'm using `getAllWithoutPhotos` and subsequently calling`getPhotoForId` as I need them.

Are you seeing any errors in logcat?

What does the data look like?  Does if have a photo uri for each contact, or is the field blank?

**Comment by raould** [comment]
In the end it was completely my own fault, passing wrong structure around. (I do have another issue with the urls being returned, but I *am* getting the urls.)
