### ISSUE TITLE
how do decode Android content:// uris?

### ISSUE THREAD

**Issue by raould** [rt2zz/react-native-contacts#183]
Does react-native-contacts have a way to convert "content://com.android.contacts/display_photo/9" to a local file uri? Or should I be using something like https://stackoverflow.com/questions/36259339/convert-content-uri-to-actual-path-for-android-using-react-native? Thanks. :)

Currently I am using Image with { uri: item.thumbnailPath } but the image ends up blank. Trying to understand the way I should be doing it. The README says that's how I should be doing it I think.

```
Displaying Thumbnails

The thumbnailPath is the direct URI for the temp location of the contact's cropped thumbnail image.

<Image source={{uri: contact.thumbnailPath}} />
```

I also just tried getPhotoForId() with the "recordID" (e.g. '9') but the callback always gets null for the url.

(I am pretty sure there are images since I can see them in the Android OS's contacts app, and could see them via a Cordova contacts app.)

**Comment by raould** [comment]
This does work, I found & fixed another issue in my layouts that was breaking the images. (If anybody else gets confused in the future: things like <Image source={uri:'content://com.android.contacts/display_photo/10'} /> does work, w/out needing more translation.)

**Comment by EyalSi** [comment]
Seems like presenting the image, as @raould wrote, is working, but copy the image with either react-native-fs or react-native-fetch-blob, fails. Seems like both of them do not support the content prefix.
Has anyone succeeded in copying those images on Android?

**Comment by EyalSi** [comment]
There is now a solution for this problem in react-native-fs. Enabling access and copy content:// files -https://github.com/itinance/react-native-fs/pull/395
