### ISSUE TITLE
Documentation not accurate - missing function `getContactsMatchingString`

### ISSUE THREAD

**Issue by niftylettuce** [rt2zz/react-native-contacts#187]
Per https://github.com/rt2zz/react-native-contacts/pull/170 - we should have a function on `Contacts` called `getContactsMatchingString`.  However this is undefined as of version 0.8.1.

**Comment by niftylettuce** [comment]
Also related to https://github.com/rt2zz/react-native-contacts/issues/167

**Comment by niftylettuce** [comment]
Can you please publish a new version to NPM from `master`?  I just installed from git and it worked fine.

**Comment by morenoh149** [comment]
Great! Just waited to see if someone could test the module before publishing.
