### ISSUE TITLE
unable to open database file (code 14)

### ISSUE THREAD

**Issue by morenoh149** [rt2zz/react-native-contacts#19]
I'm running master off github for this project. I get the following error when testing on my actual android device
![screenshot_20151216-003447](https://cloud.githubusercontent.com/assets/587438/11834093/18b2ecf8-a397-11e5-980d-c4fae0fb8000.png)
and here is an extensive logcat output with many complaints about [cursor finalized without prior close()](https://gist.github.com/morenoh149/0b5bf5d91e3b54eb566a#file-log-txt-L4847) is there a open cursor somewhere in https://github.com/rt2zz/react-native-contacts/blob/master/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java#L32 ?

I'll note the `cur` and `eCur` cursors never get `.close()` run on them.

**Comment by morenoh149** [comment]
it's also definitely not a permissions issue as when I added `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` I still got the same error.

**Comment by morenoh149** [comment]
making progress on this in feature branches

**Comment by ippa** [comment]
Trying out react-native-contacts for the first time, just trying to get Contact.getAll() working I got bitten by this. What is the recommended way of getting past this problen this now? 

Using  react-native 0.17.0. and react-native-contacts 0.1.5.

**Comment by morenoh149** [comment]
@ippa this has been fixed in master. Use a [github url](https://docs.npmjs.com/files/package.json#github-urls) until a new npm release gets cut
