### ISSUE TITLE
Can't update emailAddresses in Android

### ISSUE THREAD

**Issue by singingBoy** [rt2zz/react-native-contacts#191]
I hope update emailAddresses with new data:
![image](https://user-images.githubusercontent.com/22296047/26959347-5246c17c-4d02-11e7-840d-82e3db6c6ab7.png)

and  the result is not expected:
![image](https://user-images.githubusercontent.com/22296047/26959445-c227e160-4d02-11e7-8e20-65dd422fa116.png)

**Comment by AnkitKaneri** [comment]
Yes it fixes bugs related to add and update of phone number and email. Bt I am working on deletion of phone numbers as well as email. Where I am following approch of deletion of all phone numbers and email of perticluler contact and assigning with new updated array. As it's beong followed in iOS. This will fix all update related bugs in android
