### ISSUE TITLE
Passing getAll() contact data to ListView component

### ISSUE THREAD

**Issue by luisrowley** [rt2zz/react-native-contacts#192]
Hello everyone, I've been using this library to console.log a list of all my contacts as described in the documentation and it worked fine. 

But I'm facing problems when it comes to using the returned contact info as the 'data source' for a ListView component. Here's how my code looks like:

```js
import ContactData from 'react-native-contacts';

class ContactList extends Component {

  constructor(props) {
  super(props);

  const ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});

  this.state = {
    contacts: {},
    dataSource: ds.cloneWithRows(this.contacts),
    };

    ContactData.getAll((err, contacts) => {
      if(err === 'denied'){
        console.error(err);
      }
      else{
        this.setState({contacts: contacts});
        }
    });


  }

render() {
      return (
        <ListView style={{flex:1}}
                  dataSource={this.state.dataSource}
                  renderRow={(data) => <ContactCell {...data} onPress={() => this.props.navigation.navigate('ContactDetails', {...data})} />}
                  renderSeparator={(sectionId, rowId) => <View key={rowId} style={styles.separator} />}
                  renderHeader={() => <ListHeader />}
        />
      );
  }
}
```

The idea is to define 'contacts' as a state parameter that can then be used by ListView's dataSource. But instead this is what I get:

![screenshot_2017-06-11-14-15-08](https://user-images.githubusercontent.com/18394891/27010949-e9390586-4eb0-11e7-88a2-9a0b332c5f3c.png)

Does anyone know what's going on? Any help would be appreciated :)

**Comment by morenoh149** [comment]
> getAll (callback) - returns all contacts as an array of objects
in your code change to
```
this.state = {
    contacts: [],
    dataSource: ds.cloneWithRows(this.contacts),
    };
```
and it should work. Not a bug, developer misusing module.
