### ISSUE TITLE
getAll() returns empty array

### ISSUE THREAD

**Issue by ketankulkarni** [rt2zz/react-native-contacts#194]
```js
Contacts.getAll((err, contacts) => {
      if(err === 'denied'){
          alert("getAll denied")
       }    
       else {
                alert (JSON.stringify(Contacts));    // alerts {"myProp":"Hello"};
        }
 })
```

output - {} (empty array)
there are contacts in andoid phone

**Comment by morenoh149** [comment]
this is very confusing. you have `contacts` and `Contacts` mismatching case.
And having contacts value be `{"myProp":"Hello"}` is impossible, it must be you testing things out.

Please review your code.

**Comment by ketankulkarni** [comment]
contacts retrieved after changing Contacts to contacts in alert
