### ISSUE TITLE
Question: Expo offers contacts access. Any reason to keep this project?

### ISSUE THREAD

**Issue by morenoh149** [rt2zz/react-native-contacts#195]
I'm starting a new app and noticed Expo offers contacts bridging as well https://docs.expo.io/versions/v17.0.0/sdk/contacts.html

Any reason to keep react-native-contacts?

**Comment by rt2zz** [comment]
is there a way to use expo contacts if you are not using the expo platform?

**Comment by morenoh149** [comment]
nope. But expo is becoming pretty defacto. Closing.

**Comment by kevinleeTCA** [comment]
@morenoh149  Expo contacts only support read.
While `react-native-contacts` support create/update/delete, it need to run `react-native link ...`, which probably means that you have to eject from Expo to hook it up.

**Comment by seanahrens** [comment]
Today, if I want to use `react-native-contacts` must I eject from Expo? Or is there a way to stay with Expo and still use `react-native-contacts`?

**Comment by morenoh149** [comment]
@seanahrens you must eject from expo. And this is coming from a person that uses expo a lot. I do plan on supporting [expokit](https://docs.expo.io/versions/latest/expokit/expokit/) as I gain an understanding of it.
