### ISSUE TITLE
how to get only contacts with mobile phone?

### ISSUE THREAD

**Issue by cinder92** [rt2zz/react-native-contacts#197]
Hey thanks, it will be a great feature that we can get contacts by type of phone...

let's say, i just want to get all contacts with one or more `mobile` phone saved.

is this possible?

**Comment by cinder92** [comment]
i just figured out with javascript, but it will be better if we can do this in the native way!

```
        let filtered = [];
	contacts.filter((item,i) => {
		item.phoneNumbers.filter((phone,j) => {
			if(phone.label === "mobile"){
				filtered.push(item);
			}
		});
	});
```

**Comment by morenoh149** [comment]
user-land solution is fine for now. PR would be welcome if you implemented this natively.
