### ISSUE TITLE
Document sort order

### ISSUE THREAD

**Issue by jslz** [rt2zz/react-native-contacts#199]
Thank you for this library. One question I couldn't find answered searching in docs or issues so far: what is the intended/guaranteed sorting order? Empirically it appears to be following each platform's behaviour so on iOS I see it being sorted by last name, and on Android by first name. I think. maybe.

**Comment by morenoh149** [comment]
No sort order is imposed. The query is simply composed and the resultset is returned however the system wants. If you would prefer a default sort order please open an issue for discussion.
