### ISSUE TITLE
What is a 'contact'?

### ISSUE THREAD

**Issue by morenoh149** [rt2zz/react-native-contacts#20]
I've got a feature branch that is working on my phone.
Problem is on android I'm using [ContactsContract.CommonDataKinds.Contactables](http://developer.android.com/reference/android/provider/ContactsContract.CommonDataKinds.Contactables.html) which is a sort of pseudo join table between phone and email types.

As of now the function synchronously returns all "contacts" on the phone. A contact being objects that are "contactable". On my personal phone this returns a mix of contacts you'd find in the addressbook (phonebook) and emails I've sent from my gmail.

I could easily limit the result set to only contacts that have a phone number, [like so](https://github.com/googlesamples/android-BasicContactables/blob/fbecc41619d0c1e466cec9ea9e14863ee3f3c211/Application/src/main/java/com/example/android/basiccontactables/ContactablesLoaderCallbacks.java#L63). Thoughts @rt2zz @niftylettuce.

**Comment by niftylettuce** [comment]
I think make it simple easy fast.  We just want phone numbers and names.

**Comment by rt2zz** [comment]
@morenoh149 awesome about the progress. I agree android does not make it easy to think about contacts like an individual.

Question: is it so fundamentally different from iOS that reconciling the two into one API is not realistic?

**Comment by morenoh149** [comment]
I believe it is possible to reconcile them into one api. But with caveats.
I'll look into two things
* trying to get a first, middle and last name from the current table
* querying the `phone` table instead and peforming a right-join (sort of) into the emails table

**Comment by morenoh149** [comment]
looks like `ContactsContract.Contacts.IN_VISIBLE_GROUP` is true for the contacts you'd see in the addressbook. http://stackoverflow.com/questions/13507665/how-to-select-unique-contacts-from-android I'll just filter using this.
