### ISSUE TITLE
react-native link does not work on 0.8.2

### ISSUE THREAD

**Issue by matheusrezende** [rt2zz/react-native-contacts#201]
react-native link does not show any output, it looks like it can't find the package, rolling back to 0.8 solved the issue

**Comment by morenoh149** [comment]
Is this something that react-native-contacts needs to correct? I've never used RN link.

**Comment by matheusrezende** [comment]
In the [instalation](https://github.com/rt2zz/react-native-contacts#installation)  it says that it needs to be linked, if you do not link it shows as undefined.

**Comment by morenoh149** [comment]
again, what does this project need to change?

**Comment by matheusrezende** [comment]
@morenoh149 fix linking issues i guess?

**Comment by nonotest** [comment]
otherwise you need to manually add
```
            import com.rt2zz.reactnativecontacts.ReactNativeContacts;
            ...
            new ReactNativeContacts(),
```
in mainapplication.java on adnroid

**Comment by lambdatoast** [comment]
I confirm that `react-native link react-native-contacts` is not doing anything for some reason. It is supposed to apply the changes automatically to MainApplication, AndroidManifest, etc.

(RN 0.47 in my case)

**Comment by fredesse** [comment]
I have the exact same problem, getting "Cannot read property 'getAll' of undefined". Tried reverting back to v0.8.0 and relinking, but no luck.
Can anyone suggest a fix to this problem?

**Comment by morenoh149** [comment]
@fredesse try `rm -rf`-ing your node_modules directory

**Comment by morenoh149** [comment]
I don't know how to make the module react-native linkable. If anyone can share docs or a tutorial on how to do please share. I've removed the link step from the readme.
