### ISSUE TITLE
Please document 'err' 

### ISSUE THREAD

**Issue by jslz** [rt2zz/react-native-contacts#203]
I can't figure out from the docs how I should be testing the err value. Is it enough to do !!err? Or are there times when e.g. the err could === 'none' or something? It is a tad extra confusing to me for things like checkPermission() that gives back both an err and a permission. Thanks for any explication.

**Comment by morenoh149** [comment]
it follows typical node style
```es
fs.readFile('/etc/passwd', (err, data) => {
  if (err) throw err;
  console.log(data);
});
```
A PR making the api use promises would be welcome.
Ref http://devdocs.io/node/fs#fs_fs_readfile_path_options_callback
