### ISSUE TITLE
requestPermission doesnt prompt for permission

### ISSUE THREAD

**Issue by nitish24p** [rt2zz/react-native-contacts#208]
React native version react-native@0.45.1
react native contacts : react-native-contacts@0.6.0

```javascript
componentDidMount() {
    Contacts.checkPermission((err, response) => {
      console.log('ERROR', err)
      console.log('CHECKING PM', response)
      if (response === 'denied') {
        Contacts.requestPermission((err, res) => {
           console.log('ERROR', err);
           console.log('GRANTED', res);
        })
      }
    })
  }

```

the above code always gives ``denied`` in the GRANTED block.  And also i dont get the prompt asking for my permission to allow contacts..

**Comment by nitish24p** [comment]
This is because the two functions are doing the exact same thing as per your code in the master branch

<img width="923" alt="screen shot 2017-08-11 at 5 05 59 pm" src="https://user-images.githubusercontent.com/13037986/29211579-89a2bec8-7eb7-11e7-823f-839744218f6c.png">

**Comment by morenoh149** [comment]
@npomfret any reason you added two functions that do the same thing? do they do different things on ios?

**Comment by npomfret** [comment]
No, sorry thats a mistake

**Comment by ArcadeRenegade** [comment]
Is this fixed in the latest version?

**Comment by morenoh149** [comment]
@ArcadeRenegade no https://github.com/rt2zz/react-native-contacts/blob/master/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java#L359 PR welcome

**Comment by ArcadeRenegade** [comment]
I ended up just going with the react-native PermissionsAndroid class.

https://facebook.github.io/react-native/docs/permissionsandroid.html

**Comment by ArcadeRenegade** [comment]
Contacts.checkPermission & Contacts.requestPermission work fine on iOS though.

**Comment by morenoh149** [comment]
@ArcadeRenegade thanks for the feedback. It's very useful. We are now recommending users use https://facebook.github.io/react-native/docs/permissionsandroid.html on android and can continue using the checkPermission/requestPermission on ios.
