### ISSUE TITLE
Build error since 0.9.0

### ISSUE THREAD

**Issue by arrygoo** [rt2zz/react-native-contacts#211]
<img width="611" alt="screen shot 2017-09-11 at 11 48 13 am" src="https://user-images.githubusercontent.com/965429/30283807-2b480f20-96e7-11e7-9f2f-7c8f099fa11c.png">
Reverted back to `~0.8.0` for now. 
I'm a javascript developer so I wasn't really able to investigate this too far, let me know if I can provide more helpful information through logs or anything.

This is happening on a detached Expo.io v20 app.

**Comment by morenoh149** [comment]
yes 0.9.0 was a breaking change designed to work with RN 0.47 and above. See https://github.com/rt2zz/react-native-contacts/pull/206

**Comment by arrygoo** [comment]
Makes sense. We're on `0.46` still. Thanks for the super quick response 👍
