### ISSUE TITLE
Build error on android, RN 0.45.1

### ISSUE THREAD

**Issue by ggozad** [rt2zz/react-native-contacts#213]
Hey there,
When trying to run on android we get:
``ReactNativeContacts is not abstract and does not override abstract method createJSModules() in ReactPackage`` during build.
We use react-native 0.45.1.
Works great on iOS.

**Comment by morenoh149** [comment]
v0.9 was a breaking change it seems. I'll promote it to v1.0 as many people are reporting breakage.

To fix pin your module to v0.8 or upgrade your project to RN 0.47+

See https://github.com/rt2zz/react-native-contacts/pull/205

**Comment by saio3139** [comment]
error: ReactNativeContacts is not abstract and does not override abstract method createJSModules() in ReactPackagepublic class ReactNativeContacts implements ReactPackage {^1 error:react-native-contacts:compileReleaseJavaWithJavac FAILED

Got this module working by adding the following to ReactNativeContacts.java.

import com.facebook.react.bridge.JavaScriptModule;

@override public List<Class<? extends JavaScriptModule>> createJSModules() { return Collections.emptyList(); }
