### ISSUE TITLE
set podspecs platform to 8.0

### ISSUE THREAD

**Issue by bilalsyed001** [rt2zz/react-native-contacts#224]
On iOS 8.0 pod is failing:
`Specs satisfying the `react-native-contacts (from `../node_modules/react-native-contacts`), react-native-contacts` dependency were found, but they required a higher minimum deployment target.`

**Comment by BossKinKa** [comment]
Seem to have the same problem for iOS project, and when I tried to attach the file to the project manually, it builds failed with error ''React/RCTDefines.h' file not found"

**Comment by Jobeso** [comment]
The .podspec states `s.platform       = :ios, "9.0"` that is why it is failing on ios 8 pod. We needed to define `platform :ios, '9.0'` in our Podfile. I am not sure if this is necessary because all users of our app with ios 8 would be excluded of further support.

**Comment by morenoh149** [comment]
Closing as this project should only try to support the latest mobile OSs. Apple puts a lot of effort in upgrading user's OS so this should only have been an issue for a short amount of time.
