### ISSUE TITLE
Bundle a typing definition file for Typescript users. 

### ISSUE THREAD

**Issue by Fitzpasd** [rt2zz/react-native-contacts#225]
It would be nice if this project bundled a typing definitions for Typescript users.  Right now, TS users either have to use this library without any type checking, or roll their own.

I've composed such a definition file and sent a PR out to the commonly used `DefinitelyTyped` project [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20871).  

`react-native-contacts` doesn't appear to be actively maintained, hence why I preferred that approach.  If this issue is approved by a maintainer, I'll work to add the typings here instead.

**Comment by morenoh149** [comment]
ok
