### ISSUE TITLE
 error: ReactNativeContacts is not abstract

### ISSUE THREAD

**Issue by hszeto** [rt2zz/react-native-contacts#229]
I was just testing out this library and got the following error:
```
rt2zz/reactnativecontacts/ReactNativeContacts.java:12: error: ReactNativeContacts is not abstract and does not override abstract method createJSModules() in ReactPackage
public class ReactNativeContacts implements ReactPackage {
       ^
1 error
:react-native-contacts:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-contacts:compileReleaseJavaWithJavac'.
```

**Comment by hszeto** [comment]
I searched around and saw someone mention that upgrading to react-native 0.47 might fix it.

I'm currently running react native 0.46.4 and avoiding ever changing it. 

Any ideas on how to get around this error?

thanks.

**Comment by morenoh149** [comment]
use an older version of this project. v.40 might work https://github.com/rt2zz/react-native-contacts/releases
