### ISSUE TITLE
Android checkPermission

### ISSUE THREAD

**Issue by sm2017** [rt2zz/react-native-contacts#232]
Why checkPermission always return `authorized` even when the permission is denied
I tes0t on android 7

![image](https://user-images.githubusercontent.com/19644997/32725119-1f43e496-c889-11e7-86fa-4de7b2dfdc53.png)

**Comment by sm2017** [comment]
Help please

**Comment by morenoh149** [comment]
not sure. You can try reproducing the bug with https://github.com/morenoh149/react-native-contacts-test

**Comment by zero1108** [comment]
I encountered the same problem too. My RN version is 0.53.0, and this npm package version is 2.1.1

**Comment by morenoh149** [comment]
tracking in https://github.com/rt2zz/react-native-contacts/issues/218 please try https://facebook.github.io/react-native/docs/permissionsandroid.html out and report back.
