### ISSUE TITLE
Implement addContact for android

### ISSUE THREAD

**Issue by morenoh149** [rt2zz/react-native-contacts#24]

**Comment by morenoh149** [comment]
I haven't tested the ios implementation. @rt2zz on ios does addContact launch a dialog? Im assuming it just adds the contact and returns the result in code only.

I ask because on android many apps launch an intent and let the user add info into the native addressbook instead.

**Comment by rt2zz** [comment]
iOS does not have a built in dialog. The app should have all contact information ready and pass it to addContact as an object.

While it may exist, I do not know of an "intent" analog in iOS.

**Comment by morenoh149** [comment]
@rt2zz would you like to change the api to return the persisted contact's `recordId`? That's a very Ruby on Rails-ish way of doing things.

**Comment by rt2zz** [comment]
That sounds reasonable to me

**Comment by morenoh149** [comment]
maybe just the recordId if that's easier http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#~insertOneWriteOpResult either way it's just a thought and I'd submit it as a separate pr
