### ISSUE TITLE
android and familyName

### ISSUE THREAD

**Issue by jacargentina** [rt2zz/react-native-contacts#242]
The readme states 

## NOTE

- on Android the entire display name is passed in the givenName field. middleName and familyName will be "".

But I'm seeing that, at least on Android 8, the contacts come with familyName in place?

**Comment by morenoh149** [comment]
Haven't tested on Android 8, the behavior may have changed. If you know for sure please update the docs.

**Comment by jacargentina** [comment]
It is for sure. Not having time for the docs. Sorry

**Comment by morenoh149** [comment]
hecho
