### ISSUE TITLE
Returns Null and Undefined

### ISSUE THREAD

**Issue by mattdwardle** [rt2zz/react-native-contacts#243]
I have looked through all the existing issues and this doesn't align with linking the package still returns the required object containing all the functions. However, there is nothing inside. 

```
    getAllContacts() {
        console.log(Contacts)
        Contacts.getAll((err, contacts) => {
            if(err === 'denied'){
              // error
            } else {
              console.log(contacts);
              console.log(err);
            }
          })
    }
```

And the import:

`var Contacts = require('react-native-contacts')`

contacts returns undefined and err returns null but the Contacts object is returned with the following parameters
```
PERMISSION_AUTHORIZED:"authorized"
PERMISSION_DENIED:"denied"
PERMISSION_UNDEFINED:"undefined"
```

Any ideas?

**Comment by chensara** [comment]
Did you solve it?

**Comment by morenoh149** [comment]
tracking in https://github.com/rt2zz/react-native-contacts/issues/218 android changed their permissions model. Try https://facebook.github.io/react-native/docs/permissionsandroid.html and report back.
