### ISSUE TITLE
Changes needed for gradle 3.0.1 compatibility

### ISSUE THREAD

**Issue by pacamara** [rt2zz/react-native-contacts#247]
Some minor changes are needed for gradle 3.0.1 compatibility: in android/build.gradle:
* Remove the `buildToolsVersion`, gradle now specifies a default and the current value conflicts with that.
* Declare dependencies using `api` not `compile` per https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#new_configurations

We are currently hacking these changes with a script in status.im, and would rather it is fixed upstream. Thanks!

Parent issue: https://github.com/status-im/status-react/issues/3037

**Comment by morenoh149** [comment]
Will prioritize this for you. Exciting project you are working on @status-im.

**Comment by morenoh149** [comment]
@pacamara I see RNC is mentioned here https://github.com/status-im/status-react/wiki/React-Native-modules#module-dependencies-with-native-code but never in the code. How is it linked in?

**Comment by pacamara** [comment]
@morenoh149 Hi! That page is out of date, RNC got removed recently from status-react in this commit: https://github.com/status-im/status-react/commit/0b0405d9a5c3942d5284b50b1944bf130fb2056b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 , "[fix #3163] remove phone command". :beers:
