### ISSUE TITLE
Contact : Visible first time of fresh install

### ISSUE THREAD

**Issue by ravivlb** [rt2zz/react-native-contacts#256]
I have integrated and able to getAll contacts. But facing issue after first run.

getAll not showing data or error.

Help to solve this.

**Comment by morenoh149** [comment]
if the user does not provide access to the contacts in that first modal you must show instructions in app showing them how to enable contacts through the system. You've probably seen this pattern in other apps.

**Comment by SAHITYASAI** [comment]
@ravivlb I'm also facing the same issue. Were you able to find a solution? If yes, can you share it here asap please.
