### ISSUE TITLE
react-native link does not work 

### ISSUE THREAD

**Issue by Alver23** [rt2zz/react-native-contacts#260]
I have this problem when installing the library.
any solution ?
react-native: 0.49.3
react-native-contacts: 2.1.1
![image](https://user-images.githubusercontent.com/16018328/36819175-431c2758-1cb6-11e8-8579-0c222183fdf6.png)
@morenoh149

**Comment by morenoh149** [comment]
No clue honestly. I'm assuming you followed the readme. I'm in the middle of adding example projects to this project to ease regression testing.

**Comment by Alver23** [comment]
@morenoh149 perform these steps

yarn add react-native-contacts
react-native link react-native-contacts

then run "react-native run-android"

**Comment by lpotapczuk** [comment]
I've had the same issue.

Open your project with Android Studio and fix issues there. 

As for iOS, I had to link everything manually.

**Comment by morenoh149** [comment]
@lpotapczuk could you detail what you did in android studio. I'm starting to rewrite the installation steps to not use react-native link

**Comment by tonz341** [comment]
me too sir.
followed readme 
```
yarn add react-native-contacts
react-native link react-native-contacts

then run "react-native run-android"
```

then it will not compiled anymore stuck at 72%..

when i try from test project fresh RN it will work but not from existing package. maybe package confict?
I just use native-base

**Comment by morenoh149** [comment]
removed linking from readme.
