### ISSUE TITLE
iOS: Deprecated pod dependency

### ISSUE THREAD

**Issue by spookymodem** [rt2zz/react-native-contacts#261]
When I install this library for iOS using npm and cocoapods, one of the pod dependencies is the react pod, which causes two problems for me: (1) primary problem: I install react via npm, and this causes me to have two react installations, which leads to "ambiguous resolution" problems; and (2) secondary problem: the react pod is deprecated (not a big deal, but thought I would mention it).

**Comment by morenoh149** [comment]
@spookymodem that is a very valid point about the react pod being deprecated. Removing.
