### ISSUE TITLE
Question: Method for getting the user's contact

### ISSUE THREAD

**Issue by paintedbicycle** [rt2zz/react-native-contacts#267]
Is there a cross-platform way of returning just the contact card of the device's user? I see this was merged: https://github.com/rt2zz/react-native-contacts/pull/55 but I don't see in the docs how to access it nor if it also works on iOS

Thanks

**Comment by morenoh149** [comment]
Afaict it wasn't ported to iOS nor was it added to the Readme. Both PRs would be welcome. Closing as nonissue.
