### ISSUE TITLE
App crash getAll

### ISSUE THREAD

**Issue by danielland85** [rt2zz/react-native-contacts#268]
```sh
npm install react-native-contacts
react-native link react-native-contacts
```
> Add permission as below into android\app\src\main\AndroidManifest.xml

    <uses-permission android:name="android.permission.READ_PROFILE" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.WRITE_CONTACTS" />

> in android\settings.gradle

include ':react-native-contacts'
project(':react-native-contacts').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-contacts/android')

> in android\app\build.gradle

compile project(':react-native-contacts')

> in android\app\src\main\java\com\projectName\MainApplication.java

import com.rt2zz.reactnativecontacts.ReactNativeContacts;
 protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new ReactNativeContacts()   

> My Code
```es
import Contacts from 'react-native-contacts';

 Contacts.getAll((err, contacts) => {
        if(err === 'denied'){
          // error
          console.log('error');
        } else {
          // contacts returned in []
          console.log(contacts);
        }
      })
```

App crash when it call .getAll.

```sh
> Error msg from Logcat

D/ErrorSaveTask( 5435): mRunningTaskList.size =0
I/ErrorSaveTask( 5435): analyzeAppCrash, KEY = Exception, keyMessage =
I/ErrorSaveTask( 5435): java.lang.NumberFormatException: Invalid int: "20 May 1976"
I/ErrorSaveTask( 5435):         at java.lang.Integer.invalidInt(Integer.java:138)
I/ErrorSaveTask( 5435):         at java.lang.Integer.parse(Integer.java:410)
I/ErrorSaveTask( 5435):         at java.lang.Integer.parseInt(Integer.java:367)
I/ErrorSaveTask( 5435):         at java.lang.Integer.parseInt(Integer.java:334)
I/ErrorSaveTask( 5435):         at com.rt2zz.reactnativecontacts.ContactsProvider.loadContactsFrom(ContactsProvider.java:268)
I/ErrorSaveTask( 5435):         at com.rt2zz.reactnativecontacts.ContactsProvider.getContacts(ContactsProvider.java:141)
I/ErrorSaveTask( 5435):         at com.rt2zz.reactnativecontacts.ContactsManager$1.run(ContactsManager.java:79)
I/ErrorSaveTask( 5435):         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
I/ErrorSaveTask( 5435):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
I/ErrorSaveTask( 5435):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
I/ErrorSaveTask( 5435):         at java.lang.Thread.run(Thread.java:818)
D/ErrorSaveTask( 5435): verifyError()--occurTime: 1521112299000
```

**Comment by danielland85** [comment]
Anyone know what reason make app crash? can help?

**Comment by paintedbicycle** [comment]
Your error log says this:
`
I/ErrorSaveTask( 5435): java.lang.NumberFormatException: Invalid int: "20 May 1976"
`

Consider finding the contact that has the data "20 May 1976" in it and seeing why code is complaining that it's an "Invalid Integer". It's expecting a number, but it's finding a string. Does that contact have the full 20 May 1976 in a field that it should not? i.e. Perhaps the data in one of your contacts is in an incorrect format.

I'd first try to delete or edit that contact and see if the error persists or changes.

**Comment by danielland85** [comment]
Thanks for the advice @paintedbicycle. I have use another phone and it work fine. 
But i cannot found the contact that has the data "20 May 1976" in my first test phone. I am wonder how can i skip for searching the contact with incorrect format?

**Comment by paintedbicycle** [comment]
Since your bug is birthday related, I'd also check this PR: https://github.com/rt2zz/react-native-contacts/pull/265

**Comment by bluekey630** [comment]
I met same crash.

**Comment by Martynova** [comment]
I met crash too.

**Comment by uurtsaikhb** [comment]
I have got same crash
