### ISSUE TITLE
Add Integration tests

### ISSUE THREAD

**Issue by morenoh149** [rt2zz/react-native-contacts#27]
this is currently blocked by react-native's packager inability to follow npm linked dependencies

https://github.com/facebook/react-native/issues/637
https://github.com/facebook/watchman/issues/105

**Comment by morenoh149** [comment]
stop gap https://github.com/morenoh149/react-native-contacts-test

**Comment by morenoh149** [comment]
wondering how this worked. https://github.com/naoufal/react-native-activity-view/pull/30/files#diff-acd4a52752c7d454f1e7f4025f7d4d15R10 todo

**Comment by morenoh149** [comment]
https://github.com/morenoh149/react-native-contacts-test is working fine. It serves as a test and example of you to use the software (aka documentation).

**Comment by rt2zz** [comment]
The code in that repo reads more like a test than an implementation example. E.G. gratuitous use of `getAll`. 

Side note: travis does support iOS simulator. The thing I am unsure of is how do we get our js tests to run within the provided lifecycle... https://docs.travis-ci.com/user/languages/objective-c/
