### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by memePushpendu** [rt2zz/react-native-contacts#277]
After I install this plugin , link it & require it in app.js , the app doesn't get compiled any more . After I remove the require from app.js it compiles again.

**Comment by GeekRishabh** [comment]
@rt2zz  Any fix?

**Comment by memePushpendu** [comment]
Nothing still the same . Using [https://www.npmjs.com/package/react-native-simple-contacts](url) instead.

**Comment by morenoh149** [comment]
We can't really help you unless you provide a reproducable example. Please share a repo or zip file with your project.
