### ISSUE TITLE
Contacts.getAll works on emulator but crashes on mobile phone.

### ISSUE THREAD

**Issue by aaeronn** [rt2zz/react-native-contacts#279]
Here is my code:
```es

import React from 'react'
import { View, Text } from 'react-native'
import Contacts from 'react-native-contacts'

export default class ContactTab extends React.Component {

	componentDidMount() {

		console.log("Hello", Contacts)

		Contacts.getAll((err, contacts) => {
			console.log("dude")
		})
	}

	render() {
		return (
		  	<View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
		    	<Text>Settings!</Text>
		  	</View>
		)
	}
}
```
It works fine on emulator but crashes on phone.

The crash report only says 

```sh
I/ReactNativeJS(19364): 'Hello', { addContact: { [Function: fn] type: 'async' },
I/ReactNativeJS(19364):   checkPermission: { [Function: fn] type: 'async' },
I/ReactNativeJS(19364):   getAll: { [Function: fn] type: 'async' },
I/ReactNativeJS(19364):   getAllWithoutPhotos: { [Function: fn] type: 'async' },
I/ReactNativeJS(19364):   getContactsMatchingString: { [Function: fn] type: 'async' },
I/ReactNativeJS(19364):   getPhotoForId: { [Function: fn] type: 'async' },
I/ReactNativeJS(19364):   openContactForm: { [Function: fn] type: 'async' },
I/ReactNativeJS(19364):   requestPermission: { [Function: fn] type: 'async' },
I/ReactNativeJS(19364):   updateContact: { [Function: fn] type: 'async' } }
D/ReactNative(19364): ReactInstanceManager.detachViewFromInstance()
```

As the Contacts.getAll function gets called app crashed.

What might be the issue ? I checked the permission and it returns "authorized".

Any solution to this ?

**Comment by hungdev** [comment]
i get same error

**Comment by morenoh149** [comment]
@aaeronn what did you comment out exactly? near https://github.com/rt2zz/react-native-contacts/blob/master/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java#L257

**Comment by aaeronn** [comment]
Everything was working fine in my emulator but for my mobile the code inside the else if block was not working and raising error. I tried formatting the birthday code without double hiphen too but it didnt worked either so I commented the whole else if block, as I was not neeeding birthday from contacts.

As it was working fine on my emulator, I looked at the response but it was not giving birthday in the response. I dont know if it returns empty if not birthday or the birthday key will not be provided in the response.

**Comment by morenoh149** [comment]
if you share exactly what lines you commented out it would narrow down my investigation @aaeronn

**Comment by DimGun** [comment]
@morenoh149 I think @aaeronn means that he commented the whole block which parses birthday :)

We encountered the same issue today, one of our customers on Galaxy S7 has a contact record with the birthday "1972. 1. 15.". Will comment this block for now too.

**Comment by aaeronn** [comment]
@morenoh149 Here is what I have commented 
![nrc](https://user-images.githubusercontent.com/6998159/38425292-3529da16-39d3-11e8-98a9-fcda4566613b.png)

**Comment by faizalshap** [comment]
Do we need to edit node modules ?

**Comment by aaeronn** [comment]
@faizalshap yes you need to edit in node modules
