### ISSUE TITLE
Crash Android requestPermission

### ISSUE THREAD

**Issue by robertobrogi** [rt2zz/react-native-contacts#286]
Hi All,
I have  a big problem in Android 7.0 and 8.0.0 when i ask the permission. 
when i opne the screen, the popup with request is correct but when i tap Allow there is a crash for time out...

this is the code: 

```es
componentWillMount() {
        Contacts.checkPermission((err, response) => {
            if (response === 'denied') {
                Contacts.requestPermission((err, res) => {
                    console.log('ERROR', err);
                    console.log('GRANTED', res);
                })
            }
        })
    }
```

you know which is the problem ?

thanks a lot

**Comment by stefanedberg** [comment]
I don't know if this helps but this is how I request permission:
```

if (Platform.OS == 'android') {
    PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.READ_CONTACTS,
        {
            'title': 'Contacts',
            'message': 'Describing why I need to access contact information.'
        }
    )
    .then(granted => {
        if (granted === PermissionsAndroid.RESULTS.GRANTED) {
            Contacts.getAll((err, contacts) => {
                this.setState({
                    contacts: contacts || []
                });
            });
        }
        else {
            // Handle
        }
    })
    .catch(err => {
        console.log('PermissionsAndroid', err)
    })
}
```

**Comment by felansu** [comment]
@stefanedberg this doesn't works in android sdk 22.

**Comment by morenoh149** [comment]
@felansu sorry supporting legacy versions of android just isn't a concern for this project. If you want you can comb through the git history and see however this module used to work and submit a PR restoring those behaviors alongside the new ones.

**Comment by saibharani** [comment]
`    <uses-permission android:name="android.permission.READ_PROFILE" />
`
adding this line to AndroidManifest.xml file will solve the android crash for sdk<=22 devices.
