### ISSUE TITLE
NumberFormatException on parseInt

### ISSUE THREAD

**Issue by uriva** [rt2zz/react-native-contacts#288]
> NumberFormatException
> For input string: "28\2\1986"
> java.lang.Integer in parseInt at line 521
> java.lang.Integer in parseInt at line 556
> com.rt2zz.reactnativecontacts.ContactsProvider in loadContactsFrom at line 268
> com.rt2zz.reactnativecontacts.ContactsProvider in getContacts at line 141
> com.rt2zz.reactnativecontacts.ContactsManager$1 in run at line 79
> android.os.AsyncTask$SerialExecutor$1 in run at line 243
> java.util.concurrent.ThreadPoolExecutor in runWorker at line 1133
> java.util.concurrent.ThreadPoolExecutor$Worker in run at line 607
> java.lang.Thread in run at line 762

I believe this is a new exception from version: 2.1.3

**Comment by djhr** [comment]
having this crash too on version 2.1.2

**Comment by garethmccall** [comment]
@janpieterz is correct. I'll take a look at this today!

**Comment by garethmccall** [comment]
For now I will just add try/catch to solve the crash. But this means only contacts with birthdays in the format "1986-12-30" or "12-30" will have their birthdays imported. It is likely possible to do smarter date format detection and parsing but this is all I have time for right now.

**Comment by garethmccall** [comment]
Sorry @morenoh149 but that won't compile... pls stand by for fix
