### ISSUE TITLE
Version 2.1.4 not compiling on Android

### ISSUE THREAD

**Issue by dauane** [rt2zz/react-native-contacts#292]
Hey Guys

I just installed the new version of the library (**2.1.4**) and got a number of errors when running on Android. I was able to sort it out by simply rolling back to **2.1.3**. However, I'm sharing the issue as I believe some folks will also face it.

In essence, when I try to compile on Android, the compiler complains about 80 different statements. Below I only included a few of them but I am sure you'll be able to replicate it.

_react-native-contacts/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java:434: error: illegal start of expression
            static String getLabel(Cursor cursor) {
            ^
react-native-contacts/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java:434: error: ';' expected
            static String getLabel(Cursor cursor) {
                                  ^
react-native-contacts/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java:434: error: ';' expected
            static String getLabel(Cursor cursor) {
                                                ^
react-native-contacts/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java:448: error: class, interface, or enum expected
}
^
80 errors
:react-native-contacts:compileReleaseJavaWithJavac FAILED_

My app is running on:
- "react": "16.2.0",
- "react-native": "0.53.0"

**Comment by garethmccall** [comment]
fixed in my PR #291
