### ISSUE TITLE
how to get contact by using query phone number

### ISSUE THREAD

**Issue by hungdev** [rt2zz/react-native-contacts#295]
Currently, getContactsMatchingString just get contact match a name (first, middle, family). Could anyone tell me how to get contact match phone number?

**Comment by morenoh149** [comment]
dupe  https://github.com/rt2zz/react-native-contacts/issues/137

**Comment by hungdev** [comment]
thank for your reply @mehcode.
but that post locked or limited comment:
`Repository owner locked and limited conversation to collaborators on Dec 28, 2016`

**Comment by morenoh149** [comment]
unlocked. Don't remember doing that years ago.
