### ISSUE TITLE
Android: Callback isn't called on requestPermission

### ISSUE THREAD

**Issue by qmegas** [rt2zz/react-native-contacts#297]
Library version: 2.1.5
React Native: 0.55.3
Platform: Android

Here is my simple code:
```
Contacts.checkPermission((err, res) => {
	if (res === 'denied') {
		Contacts.requestPermission((err, res) => {
			console.log('requestPermission result', res);
		});
	}
});
```
When request permission dialog appears, after I choose Deny or Accept the callback of  `requestPermission` never called.

Should it work that way or it's a bug?

**Comment by morenoh149** [comment]
the permission related methods are only useful on ios. For android use `permissionsandroid` See https://github.com/rt2zz/react-native-contacts#permissions-methods-optional
