### ISSUE TITLE
ContactsProvider.java:299: error: cannot find symbol Log.w in 2.1.6

### ISSUE THREAD

**Issue by lfiorini** [rt2zz/react-native-contacts#298]
> Task :react-native-contacts:compileReleaseJavaWithJavac FAILED 
.../ContactsProvider.java:299: error: cannot find symbol                         Log.w("ContactsProvider", e.toString());                         ^   symbol:   variable Log   location: class ContactsProvider 1 error   FAILURE: Build failed with an exception.  * What went wrong: Execution failed for task ':react-native-contacts:compileReleaseJavaWithJavac'. > Compilation failed; see the compiler error output for details.

**Comment by maorshabo** [comment]
I've got this error too :(
