### ISSUE TITLE
AddressBook is not defined

### ISSUE THREAD

**Issue by JoaoCnh** [rt2zz/react-native-contacts#3]
Hey I just started using this and when I try to request permission it throws an error about AddressBook not being defined.

In the AddressBook.requestPermission line.

How can I include AddressBook? I can't seem to find it in the docs

**Comment by rt2zz** [comment]
this is a bug, I will resolve today.

In the meantime it is very unlikely you need to call request permission as this is automatically handled when you call 'getAll'

**Comment by rt2zz** [comment]
Actually, this was just a case of an out of date readme. Change `AddressBook.requestPermission` to `Contacts.requestPermission`.

I just updated readme as well
