### ISSUE TITLE
rename recordID to id

### ISSUE THREAD

**Issue by rt2zz** [rt2zz/react-native-contacts#30]
also we should consider how id handling is different in android vs iOS (in ios record id's are somewhat transient)

**Comment by morenoh149** [comment]
could you expand on this? you want to rename the recordID field to id on both platforms?

**Comment by rt2zz** [comment]
Ya. Originally I named it recordID to parallel the terminology of iOS AddressBook. But this feels arbitrary, and its weird in camel case should it actually be recordId? But then in Contacts framework they use "identifier" and in android it is "id" I believe - so recordID feels antiquated.

This would be a major breaking change but migration would be trivial. Thoughts?

**Comment by morenoh149** [comment]
trivial agreed. I would just change this line https://github.com/rt2zz/react-native-contacts/blob/master/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java#L77

**Comment by sibelius** [comment]
just release a new major release with this
