### ISSUE TITLE
Installing module includes an 'example' folder that causes a  @providesModule warning

### ISSUE THREAD

**Issue by PhoenixRe32** [rt2zz/react-native-contacts#300]
I am using:

- NodeJS 8.11.1
- NPM 6.0.1
- react-native-contacts 2.1.7

After installing it I got the following warning on the metro packager when trying to run the react-native app on my emulator
```
This warning is caused by a @providesModule declaration with the same name across two different files.
Loading dependency graph, done.
error: bundling failed: ambiguous resolution: module `/Users/user/Projects/Mine/app/app-client/index.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them: 

  * `/Users/user/Projects/Mine/app/app-client/node_modules/react-native-contacts/example/node_modules/react-native/package.json`
  * `/Users/user/Projects/Mine/app/app-client/node_modules/react-native/package.json`
```

I checked the zip in the releases section but it doesn't seem to have an example folder inside. 
Deleting seems to fix the problem but not sure where the folder comes from

**Comment by morenoh149** [comment]
try now, that's a wip example project that should help catch regressions.

**Comment by PhoenixRe32** [comment]
Yup, it's fine now.
There is no example folder being created
May I ask how that folder was being created? Kind of new to the workings of NPM but I didn't see it in the source code anywhere so I am thinking that it was being added by the NPM installation?

**Comment by morenoh149** [comment]
basically npm and github are different sources for the code. Usually master on github is what ends up on npm but it's not guaranteed. In this case I accidentally published the example dir to npm.
