### ISSUE TITLE
android7 Flash back

### ISSUE THREAD

**Issue by dltjiangfeipeng** [rt2zz/react-native-contacts#304]

**Comment by morenoh149** [comment]
what does this mean?

**Comment by dltjiangfeipeng** [comment]
在安卓版本5.0.2没有问题 显示正常，但是在版本7.0就出现闪退，没有任何提示，直接退出App

**Comment by dltjiangfeipeng** [comment]
There is no problem in android version 5.0.2, but in version 7.0, there is a flash back, without any prompt, and directly exit the App

**Comment by DamonChenXL** [comment]
you have to get PermissionsAndroid First ,and then use Contacts to getAll
