### ISSUE TITLE
 fatal error: 'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by jcekstrom** [rt2zz/react-native-contacts#305]
When using with CocoaPods, I get the following:
`fatal error: 'React/RCTBridgeModule.h' file not found`

It can be fixed easily by adding:
`s.dependency 'React/Core'` to the podspec file.

**Comment by jcekstrom** [comment]
#306 Fixes this issue for me.

**Comment by morenoh149** [comment]
@jcekstrom does https://github.com/rt2zz/react-native-contacts/pull/230 fix the issue for you?

**Comment by catherinetcai** [comment]
+1 This fixes the issue for me as well.

I added the line and then did a `pod install` and it fixed the issue for me.

**Comment by haiifeng** [comment]
@catherinetcai  can i ask you how to do with step by step?  i really really do not know that.

**Comment by morenoh149** [comment]
@OceanHorn quote
When using `cocoapods `to install RN dependencies like `react-native-contacts` and so on, developer should *also* install `React` using `cocoapods`. When a dependency like `React` point to local folders has been defined in the `Podfile` of the project, the `React` dependency defined in the `react-native-contacts.podspec` is point to the same `React`.

Your Podfile should look like
```
node_modules_path = "../node_modules"
# some other dependencies like react-native-contacts
pod "react-native-contacts", :path => "#{node_modules_path}/react-native-contacts"

# react-native dependencies
react_native_path = "#{node_modules_path}/react-native"

pod "yoga", :path => "#{react_native_path}/ReactCommon/Yoga"
  pod "DoubleConversion", :podspec => "#{react_native_path}/third-party-podspecs/DoubleConversion.podspec"
  pod "glog", :podspec => "#{react_native_path}/third-party-podspecs/glog.podspec"
  pod "Folly", :podspec => "#{react_native_path}/third-party-podspecs/Folly.podspec"

# React
pod "React", :path => react_native_path, :subspecs => [
      "Core",
      #"BatchedBridge",
      "CxxBridge",
      "DevSupport",
      #"tvOS",
      #"jschelpers_legacy",
      #"cxxreact_legacy",
      "jschelpers",
      "PrivateDatabase",
      "cxxreact",
      "ART",
      "RCTActionSheet",
    #"RCTAdSupport",
      "RCTAnimation",
      "RCTBlob",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTPushNotification",
      "RCTSettings",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "fishhook",
      "RCTLinkingIOS",
      "RCTTest",
    #"_ignore_me_subspec_for_linting_",
      ]
```

**Comment by morenoh149** [comment]
@haiifeng another example https://github.com/msand/SVGPodTest/blob/master/ios/Podfile#L12
