### ISSUE TITLE
Feature Request: Add support for Websites/ URLs for contact creation

### ISSUE THREAD

**Issue by freeminders123** [rt2zz/react-native-contacts#310]
Hi,
we've been working on an app where users are able to provide vCards over a web interface and other users should be able to add the data directly to their contacts on the phone. As we are having business customers on the web-part, it is quite essential, that we can add web-addresses. 
For iOS this would mean adding urlAddresses for the contact object (like with mail and so on) as [CNLabeldValue<NSString>];

For Android it is documented here: https://developer.android.com/reference/android/provider/ContactsContract.CommonDataKinds.Website

I would really appreciate it if you could bring this soon to a next update.

If you need help in implementing this, let me know. (For now I thought some of you guys are quicker in adding this, than me with first installing and getting the prerequisites in place).

Thanks in advance

P.S.: If no one can implement this, could you tell me, how long it would take, if I created a pull request for the change to make it to a new release?

**Comment by morenoh149** [comment]
No one is currently working on new features atm. I'm working on adding an example to this project to ease development (this is a priority).

PRs are very welcome and if you assert that it works I'm more than happy to merge it as soon as I skim through it. It'd be in the next version of the module and that'd be available immediately.

**Comment by freeminders123** [comment]
Thanks for the response @morenoh149 I'm going to implement this and create a pull request in the next 1-2 weeks.

**Comment by i3i2uno** [comment]
@freeminders123 any update for the mentioned Enhancement?

**Comment by morenoh149** [comment]
no

**Comment by mmarvick** [comment]
I think this issue can be closed (by PR #329)

**Comment by shubham-cpp** [comment]
Has this been removed in 7.0.5?
I have a story that also requires to fetch the urlAddress of contact.

Info:
Node: v18
React Native: 0.72.1
React Native Contacts: 7.0.5
Android SDK: 33

**Comment by morenoh149** [comment]
@joaonew no it wasn't. Feel free to add that.
