### ISSUE TITLE
RCTContacts.xcodeproj cannot be added in XCode!

### ISSUE THREAD

**Issue by wzup** [rt2zz/react-native-contacts#311]
Your manual installation section is wrong.
`RCTContacts.xcodeproj` can't be added that way, it is not selectable.

![screen shot 2018-07-02 at 8 29 13 pm](https://user-images.githubusercontent.com/3880497/42177833-d86b2962-7e36-11e8-982b-fcc425feeca7.png)

**Comment by adbarmand** [comment]
Did you already run `react-native link react-native-contacts` ?
If so, the library might be added already, and that's why you cannot select it.

**Comment by morenoh149** [comment]
@adbarmand should the react-native link step be removed altogether? it seems like it doesn't work

**Comment by morenoh149** [comment]
updated the instructions to more closely match the RN docs, @wzup lmk if it works

**Comment by morenoh149** [comment]
updated docs and verified that you can link the lib, removed the image.
