### ISSUE TITLE
add an eventListener on change

### ISSUE THREAD

**Issue by yannoudou** [rt2zz/react-native-contacts#314]
add an eventListener , that tell me when there is a change in the contacts, like new records or any change (name,number,mail...).
Is there any way to achieve this?

**Comment by morenoh149** [comment]
You'd have to implement it into the api.

**Comment by morenoh149** [comment]
@sganti564 no eta on this feature. I'd estimate it's medium difficulty if you know the apis, hard if you don't.

for ios something like https://developer.apple.com/documentation/foundation/nsnotification/name/1403253-cncontactstoredidchange and then bubble an event into javascript https://facebook.github.io/react-native/docs/native-modules-ios.html#sending-events-to-javascript

for android https://developer.android.com/reference/android/database/ContentObserver.html#onChange(boolean) and https://facebook.github.io/react-native/docs/native-modules-android.html#sending-events-to-javascript

**Comment by morenoh149** [comment]
dupe https://github.com/rt2zz/react-native-contacts/issues/57

**Comment by vivek0046** [comment]
any update on this ?

**Comment by humaidk2** [comment]
I would like to try to tackle this issue, if this lib is still accepting prs

**Comment by humaidk2** [comment]
dupe of this too [#637 ](https://github.com/morenoh149/react-native-contacts/issues/637)

**Comment by vivek0046** [comment]
> I would like to try to tackle this issue, if this lib is still accepting prs
@morenoh149 i think he is the author and active here

**Comment by humaidk2** [comment]
So looked into it today, was able to add the ios event.

but it doesn't have any data on which contacts changed, just that there was an update and you have to repull ur contacts.

I did find this, but it only supports ios 13 and above, is it alright to have methods that only support ios13+?

https://developer.apple.com/documentation/contacts/cncontactstore/3294190-enumeratorforchangehistoryfetchr?language=objc

**Comment by vivek0046** [comment]
turns out android does have this feature ,its called sync adapter and it marks contacts as dirty if there have been updated since last sync.

https://developer.android.com/identity/providers/contacts-provider#SyncAdapters

**Comment by morenoh149** [comment]
@humaidk2 its ok to support the latest version of ios.
