### ISSUE TITLE
Cannot read property 'checkPermission' of undefined

### ISSUE THREAD

**Issue by wzup** [rt2zz/react-native-contacts#316]
I've read this https://github.com/rt2zz/react-native-contacts/issues/147 but I still have this problem. Linking doesn't solve the issue.

I also enabled `Privacy - Contacts` in my `.plist` file.

Why error? How to solve?

**Comment by wzup** [comment]
This is what actually fixed the issue

https://github.com/rt2zz/react-native-contacts/issues/220#issuecomment-367287134

Sometimes `$ react-native link` is not enough.

**Comment by felipesousa** [comment]
I'm also, I'm trying delete the `node_modules` and `package-lock.json` but no success so far :/

**Comment by felipesousa** [comment]
I fix trying add the dependencie mannualy: https://github.com/rt2zz/react-native-contacts#manual
