### ISSUE TITLE
Cannot read property 'getAll' of undefined

### ISSUE THREAD

**Issue by tusharkhatiwada** [rt2zz/react-native-contacts#317]
Hi there,
I've installed the component and have linked manually but I'm getting `Cannot read property 'getAll' of undefined`.

I added **'READ_CONTACTS'** permission in AndroidManifest.xml file have also handled Permission using PermissionAndroid. When I call `getAll` method I get the above error. Also I tried to console log `Contacts` component, I'm getting it **undefined**.

If I use auto link with `react-native link react-native-contacts` and build using `run-android` I get following error: 

`AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.`

**Comment by tusharkhatiwada** [comment]
I forced all the dependencies to use the following SDK version and it worked.

**android/build.gradle**

```
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 27
                buildToolsVersion "27.0.3"
            }
        }
    }
}
```

**Comment by morenoh149** [comment]
@tusharkhatiwada should the readme be updated?

**Comment by tusharkhatiwada** [comment]
@morenoh149 I think so. Also there is no enough details on how to manually link for **Android**.
