### ISSUE TITLE
Error: Naming collision detected

### ISSUE THREAD

**Issue by nbastoWM** [rt2zz/react-native-contacts#32]
Packager gives this error:

```
 Error: Naming collision detected: 
/Users/wiremaze/wm/dev/WMMyCityApp2/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js 
collides with 
/Users/wiremaze/wm/dev/WMMyCityApp2/node_modules/react-native-contacts/test/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js
```

I had to remove the ```react-native-contacts/test``` folder, as a number of files colides.

**Comment by tomauty** [comment]
Yeah I did this as well. Couldn't figure out where it's coming from, either. No mention of `test` in the repo.

**Comment by morenoh149** [comment]
no mention of test in the source either

**Comment by tomauty** [comment]
I'm guessing it was deployed to npm without being pushed to GH.

**Comment by morenoh149** [comment]
Interesting. That was me. I assumed npm publish only shares what's under git version control. But it shares all the files in the directory. Will fix soon.

**Comment by tomauty** [comment]
Works for me now :+1:
