### ISSUE TITLE
getAll doesn't return updated contacts

### ISSUE THREAD

**Issue by pravinraut809** [rt2zz/react-native-contacts#327]
I found that getAll method doesn't return contact which got updated. Suppose i go and update the name of some contact then it will not appear in the list

**Comment by rohit75** [comment]
Facing the same issue.

**Comment by morenoh149** [comment]
are you seeing this on both platforms?

**Comment by rohit75** [comment]
On android only

**Comment by samcorcos** [comment]
@morenoh149 I'm running into this issue on iOS as well, though I'm also finding that the `getAll` method appears to only return about 1/3 of my contacts. Not sure how to diagnose.

**Comment by morenoh149** [comment]
not sure. For large number of records we want to add pagination but at the moment the phone crashes if it runs out of memory.

You are describing another issue.

**Comment by DaveLomber** [comment]
Same is here on Google Pixel 
Seems it's device specific, since it works well on some devices

Any solutions?

**Comment by DaveLomber** [comment]
Ok seems the issue is clear somehow 

this is about linked accounts

I have a main account and a Viber account linked to it
If I change a name of main account, an old name from Viber account is still returned 

any ideas on how to fix it?

**Comment by DaveLomber** [comment]
Found a root cause - it overrides the contact here https://github.com/rt2zz/react-native-contacts/blob/master/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java#L277

**Comment by DaveLomber** [comment]
The temp workaround for this is to rely on 'displayName' rather given & family name
since a 'displayName' is updated correctly 

I prepared a PR for this 
https://github.com/rt2zz/react-native-contacts/pull/405
