### ISSUE TITLE
Add checkPermission for Android

### ISSUE THREAD

**Issue by pickhardt** [rt2zz/react-native-contacts#33]
Can you add checkPermission for Android, and to the status table in the readme? I couldn't tell whether it's supported on Android. From reading further on it looks like it is iOS only, not entirely sure though so I thought I'd ask.

**Comment by rt2zz** [comment]
Probably a good idea. PR perhaps? 

With android permissions are typically requested upon install. I know there are now on demand permissions in android 6 though so it would make sense to support both modes.

**Comment by morenoh149** [comment]
I think you can do that in android too https://developer.android.com/training/permissions/requesting.html

**Comment by pickhardt** [comment]
Well, now I'm seeing this error in Android because the checkPermission function isn't defined. @morenoh149 are you saying it exists in Android, and what should I use instead?

**Comment by morenoh149** [comment]
I'm saying it may be feasible in Android. Someone just has to code it.
