### ISSUE TITLE
Android API level 22 crashes on `getAll()`

### ISSUE THREAD

**Issue by platonish** [rt2zz/react-native-contacts#331]
Whenever I tried to access contacts through the `getAll()` method on a Nexus 4 running Android 5.1.1 Lollipop (API level 22), the app would immediately crash without warning. I checked logcat, and found out that a permission for `READ_PROFILE` was also required. I added that to AndroidManifest.xml and everything worked fine.
Also, the permission granted status is represented as a boolean `true` value rather than the string `'granted'`. This is also a condition that needs to be handled separately for older versions of Android (<= API level 22).

I can create a quick PR for handling this case.

**Comment by jamalhassouni** [comment]
+1

**Comment by morenoh149** [comment]
yes if you can submit a PR that supports older versions of android and maintains support for new versions of android as well that would be appreciated @platonish

**Comment by platonish** [comment]
Hi @morenoh149, sorry for the late response. Actually on second thought, I think it would be better if we simply added a note in the readme regarding this, so that those who don't require it aren't requesting unnecessary permissions. LMK what you think.

**Comment by morenoh149** [comment]
@platonish yes absolutely. If you open PR for the readme I'll merge. Basically, you're suggesting we also list `READ_PROFILE` in https://github.com/rt2zz/react-native-contacts#android-1 ?

**Comment by platonish** [comment]
@morenoh149 yup pretty much! Take a look 🙂

**Comment by ssancheza227** [comment]
Hi @morenoh149, i have same problem :/ and added the permissions  <uses-permission android:name="android.permission.READ_PROFILE" /> but this not working :/. Do i have to do something else?

**Comment by morenoh149** [comment]
@ssancheza227 are you having issues on both platforms? usually the issue is not following the instructions correctly, read the whole readme first then try to install it.

**Comment by ssancheza227** [comment]
@morenoh14 I have the problem only in android but only in versions custom for example v5.1.1 in this version the app crash but in v5.0 the app work, maybe i have the force the version in build.gradle :/.

**Comment by jamalhassouni** [comment]
I've had the same problem before
The problem was that the phone number was null
You have resolved it by displaying data if the phone number is not = null

**Comment by ssancheza227** [comment]
@jamalhassouni Great! you would shared your solution in code?  please :)
