### ISSUE TITLE
Could not find method google() for arguments [] on repository 

### ISSUE THREAD

**Issue by krishna201** [rt2zz/react-native-contacts#341]
* What went wrong:
A problem occurred evaluating project ':react-native-contacts'.
> Could not find method google() for arguments [] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

Please help to resolve the issue.

**Comment by morenoh149** [comment]
not sure

**Comment by vkandk** [comment]
@krishna201  add google() to ./<project-name>/android/build.gradle

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        jcenter()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url "https://maven.google.com" }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

**Comment by sohagfaruquebd** [comment]
Same issue here.

**Comment by krishna201** [comment]
i resolve the issue
update the gradle to 4.5
by going andorid/gradle/wrapper/gradle-wrapper.properties
to distributionUrl=https\://services.gradle.org/distributions/gradle-4.5-all.zip
then react-native run-android
enjoy
