### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_reactNativeContacts.default.checkPermission') 

### ISSUE THREAD

**Issue by SyedRahim** [rt2zz/react-native-contacts#344]
The contacts is perfectly working on android but in iOS it's throwing this error.

**Comment by KonradIT** [comment]
Same problem on Android.

**Comment by abdulbasit1248** [comment]
For ios you have to do little work in xcode.
Open xCode > click on libraries in left side> expand RCTContacts.xcodeproj> and find libRCTContacts.a file in it 
now go to build phases tab by clicking the project name on the top. then drag this file(libRCTContacts.a) in the link binaries with libraries under the build phases tab . remove the already present libRCTContacts .
Make sure you have added a property "privacy-contacts usage description" in info.plist file
You are good to go 
@nandhu143  @KonradIT

**Comment by SyedRahim** [comment]
Thank you @abdulbasit1248
