### ISSUE TITLE
getAll crash when having many contacts

### ISSUE THREAD

**Issue by pourabbas** [rt2zz/react-native-contacts#347]
hi
When using getAll on a phone with many contacts (like 1000 or more), app crashes with MemoryException.
How can I handle that?

**Comment by morenoh149** [comment]
Which platform? Which device model? Which operating system version number?

This may require changing the api to support pagination.

**Comment by iagorm** [comment]
I have the same issue with a user, his device details:

Platform: android
Brand: HUWAEI
Android device: ANE-LX1
Android os version 8.0.0

**Comment by morenoh149** [comment]
duplicate #226
