### ISSUE TITLE
App crashing when contacts permissions are denied

### ISSUE THREAD

**Issue by kottamasusaikumar** [rt2zz/react-native-contacts#357]
How can i manage the denied permissions to not to crash the app

**Comment by morenoh149** [comment]
please share a gif of what you're talking about. Permission requesting is only available on iOS. https://github.com/rt2zz/react-native-contacts#permissions-methods-optional

**Comment by kottamasusaikumar** [comment]
Thank you the issue had fixed

**Comment by kottamasusaikumar** [comment]
Issue had fixed
