### ISSUE TITLE
update readme MainActivity.java

### ISSUE THREAD

**Issue by pickhardt** [rt2zz/react-native-contacts#36]
My MainActivity.java has the following:

```
public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "App Name Goes Here";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

   /**
   * A list of packages used by the app. If the app uses additional views
   * or modules besides the default ones, add more packages here.
   */
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage()
      );
    }
}
```

The README just says add the code to MainActivity.java, but it doesn't say where. What part of the file does it go in?

**Comment by morenoh149** [comment]
the readme does say where but your mainactivity.java file looks very different. Is it at the same directory specified in the readme? if so then perhaps RN has changed the structure of the generated file?

**Comment by pickhardt** [comment]
Yes, it's the same file. I am on RN 0.19.0 - I figured it was probably just that RN has changed since this was written.

**Comment by morenoh149** [comment]
yep it's changed dramatically https://github.com/facebook/react-native/commit/935cbb76c02cffd378a8f391c6e7443a3da13adc mind giving updating the docs a shot?

**Comment by pickhardt** [comment]
I mean, if I knew what to do I would say it here, but I don't know what to do...

**Comment by pickhardt** [comment]
I think you just add it to getPackages

Going to try that now.

**Comment by pickhardt** [comment]
Well, when I add it to getPackages, it doesn't compile and get this error:

```
/Users/jrp/projects/myapp/node_modules/react-native-contacts/android/src/main/java/com/rt2zz/reactnativecontacts/ReactNativeContacts.java:16: illegal start of type
    List<NativeModule> modules = new ArrayList<>();
                                               ^
1 error
:react-native-contacts:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-contacts:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by pickhardt** [comment]
OK, that seems like it - you just have to add the package in the list in getPackages

**Comment by pickhardt** [comment]
Solved with https://github.com/rt2zz/react-native-contacts/pull/37

**Comment by morenoh149** [comment]
:+1: Indeed android does not support modern Java language versions.
