### ISSUE TITLE
Issue with Huawei phones

### ISSUE THREAD

**Issue by luucv** [rt2zz/react-native-contacts#366]
For android my implementation works good on all devices I tested. Except for Huawei, which I don't have myself, I'm getting the error `java.lang.IllegalArgumentException: the bind value at index 1 is null` in my crash reporter for `updateContact`. I tried exactly the same inputs as this user tried on another non-Huawei phone and it worked fine.

Does anyone know about any differences between the Huawei contacts interface and the standard Android interface?

This might be related:
https://stackoverflow.com/questions/10014832/getting-account-type-of-contacts-table-for-accessing-phone-contact

**Comment by rcidt** [comment]
Why was this closed? Did you resolve this? @luucv
