### ISSUE TITLE
openContactForm not opening in iPhone

### ISSUE THREAD

**Issue by vaibhav22c** [rt2zz/react-native-contacts#368]
openContactForm not opening in iPhone but it's working on android

**Comment by morenoh149** [comment]
are you seeing any error? please share an example project on GitHub.

The iOS function is here https://github.com/rt2zz/react-native-contacts/blob/master/ios/RCTContacts/RCTContacts.m#L430

**Comment by vaibhav22c** [comment]
```
addContact() {
    var newPerson = {
      phoneNumbers: [{
        label: "",
        number: this.state.userdata.mobileNo,
      }]
    }
    console.log('***'); // this log printed
    Contacts.openContactForm(newPerson, (err, contact) => {
      console.log('--------');
      if (err) {
        console.log('--------err', err);
      }
      else {
        console.log('=====save successful====');
      }
    })
  }
```

not getting error or result, also working fine in android.I try to many time config and linking library but nothing

**Comment by morenoh149** [comment]
@vaibhav22c are you having issues with all of this libraries commands on iOS?

**Comment by vaibhav22c** [comment]
this issue is solve 
i remove` pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'` from my pod file.

but i wan't to save in ExistingContact with openContactForm (like whatsApp) it's possible ? if yes then how ?

**Comment by morenoh149** [comment]
you want to update a contact with openContactForm ?

**Comment by vaibhav22c** [comment]
yes

**Comment by morenoh149** [comment]
not sure it's possible. @xyuka can a contact be updated via the native contact form on the phone?

**Comment by abhi-nahi** [comment]
Not sure, but what documentation says that openContactForm will open add contact UI of native before saving it to the local device which is not working on IOS device.
![Screenshot 2019-07-16 at 11 33 53 AM](https://user-images.githubusercontent.com/46667202/61270004-f013d580-a7bd-11e9-91ca-77c5a4501d43.png)
