### ISSUE TITLE
when I want to call getAll function my app is show me Unfortunately, *** has stopped

### ISSUE THREAD

**Issue by sunithakk** [rt2zz/react-native-contacts#370]
I installed it and I added this permission on manifest.xml :

<uses-permission android:name="android.permission.READ_CONTACTS" />

but when I want to call getAll function my app is show me Unfortunately, *** has stopped
```
componentDidMount(){
   Contacts.getAll((err, contacts) => {
  if (err) throw  err

    //console.log(contacts)
  })
 }
```

**Comment by morenoh149** [comment]
I cannot debug this as is. Did you read the _entire_ readme?

**Comment by muZk** [comment]
Remember to ask permissions. read [here for ios](https://github.com/rt2zz/react-native-contacts#ios-1), [here](https://github.com/rt2zz/react-native-contacts#android-permissions) and [here](https://github.com/rt2zz/react-native-contacts#android-1) for android.

**Comment by pspankaj** [comment]
I m getting the same issue after giving all permissions from readme.md. Please help

**Comment by morenoh149** [comment]
@pspankaj @sunithakk please share an entire example that behaves like this. A GitHub repo I can clone and what command to run to see the error.

**Comment by pspankaj** [comment]
Issue solved for me.. As I was using api below 22. And I did not given the read_profile permission.
