### ISSUE TITLE
Does not work with updated JSC on Android

### ISSUE THREAD

**Issue by moritzw1** [rt2zz/react-native-contacts#372]
When using with an updated version (236355) of JSC there is an error in the build (run-android) process:

`Task :react-native-contacts:compileDebugJavaWithJavac FAILED`

```
node_modules/react-native-contacts/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java:50: 
error: ContactsManager is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
public class ContactsManager extends ReactContextBaseJavaModule implements ActivityEventListener {
```

**Comment by morenoh149** [comment]
@moritzw1 how did you update the jsc?

**Comment by moritzw1** [comment]
Updating to React Native 0.59 solved this issue as there is no need to use the updated JSC anymore and the plugin works fine.
