### ISSUE TITLE
iOS 12.2 screen with contacts opens and closes immediately

### ISSUE THREAD

**Issue by latusdenis** [rt2zz/react-native-contacts#379]
After upgrading to iOS 12.2 on some devices contacts crashes (Screen opens and closes immediately). Using the latest version of contacts. What can be the problem?

**Comment by morenoh149** [comment]
this is commonly a problem with how you installed the module. Please doublecheck the instructions. If that doesn't work try downgrading the iOS version and see if that fixes it.

**Comment by latusdenis** [comment]
@morenoh149 The library is set up correctly. This problem occurs in rare case only on iOS 12.2. Can it be somehow connected with lib core?

**Comment by morenoh149** [comment]
anything is possible. This sounds hard to debug though. Anything you can share to help debug it I'd appreciate!

**Comment by latusdenis** [comment]
@morenoh149 The issue was solved by upgrading from RN 0.57.7 to 0.59.4. Thanks for your reply!
