### ISSUE TITLE
Which accounts/sources/destinations are used?

### ISSUE THREAD

**Issue by Dexwell** [rt2zz/react-native-contacts#388]
Thanks for this project!

I was wondering how it is decided where a contact gets updated or created if this library is used.

For example, on iOS: is a contact created in the Local account container, or a random account like iCloud? Can we specify? And if we read a contact (which is a Unified Contact) and update it, to which account are the changes saved?

Same question on Android, and is it possible to act as a separate [Contacts Provider](https://developer.android.com/guide/topics/providers/contacts-provider) working with its own raw contacts using this library?

**Comment by morenoh149** [comment]
not sure
