### ISSUE TITLE
import returns undefined in iOS simulator, but connected device is fine

### ISSUE THREAD

**Issue by herstand** [rt2zz/react-native-contacts#394]
When I build from XCode onto my connected iOS 12.2 iPhone X, I am able to load contacts as expected using this module. 

But when I run `react-native run-ios` in the terminal and load the app in the iOS 12.2 iPhone X simulator, the following import statement sets Contacts to `undefined`:

```
import Contacts from 'react-native-contacts';
```

Any idea why?

**Steps I've already done:**

In my package.json, I have:
```
"react": "16.6.3",
"react-native": "0.58.6",
"react-native-contacts": "^4.0.2"
```

I ran:
```
watchman watch-del-all &&
rm -rf $TMPDIR/react-native-packager-cache-* &&
rm -rf $TMPDIR/metro-bundler-cache-* && 
rm -rf node_modules/ && 
yarn cache clean &&
rm yarn.lock &&
yarn install
```

I linked in XCode by going to the Build Phases tab, expanding "Link Binary With Libraries", and dragging over libRCTContacts.a from the Project navigator.

I added the following to my Info.plist file:
```
<key>NSContactsUsageDescription</key>
<string>Enable $(PRODUCT_NAME) to access your contacts to invite your friends.</string>
```

I have run "Erase all Content and Settings" in the simulator.

The Contacts app in the Simulator shows 6 default contacts when the app is loaded.

I have tried all these steps while running node v12.3.1, and also while running node v10.16.0, but I get the same results either way.

All other react-native libraries I'm using import and work fine in the simulator in this same app.

![image](https://user-images.githubusercontent.com/950515/58738009-e1ba5780-83d1-11e9-9961-6f89d21c1d46.png)

![image](https://user-images.githubusercontent.com/950515/58738019-ef6fdd00-83d1-11e9-840d-060095447ff7.png)

**Comment by viet0511** [comment]
I facing same error. Contacts is undefined.
"dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-contacts": "^4.0.2"
  }
![image](https://user-images.githubusercontent.com/1768904/58742409-3d76f600-844f-11e9-9275-673bdcd5c296.png)

**Comment by morenoh149** [comment]
Not sure, usually people get the software working in an emulator and run into issues on real devices. You are experiencing the opposite.

**Comment by herstand** [comment]
I ran `Clean Build Folder` from XCode and the problem persisted. 

But then I deleted my `ios/build` folder and reran `react-native run-ios` and things started working.
