### ISSUE TITLE
Keep AddressBook framework for project that need to be < iOS 9 compliant

### ISSUE THREAD

**Issue by JeanLebrument** [rt2zz/react-native-contacts#4]
Hello,

Thanks for the work made so far. I used the `react-native-addressbook` package and switched on `react-native-contacts`. 

I took a look to the Readme file and I saw that you want to migrate to the new `Contacts Framework`
This framework is IOS9+ compliant, but a lot of projects need to stay iOS7/iOS8 compliant. 

Do you plan to keep a version of this package compliant for < iOS9 version?

Best,
Jean

**Comment by rt2zz** [comment]
Yes this project will remain backwards compatible for some time. Although new features like groups support will likely only be ios 9+ only.

**Comment by bdbergeron** [comment]
Just curious about whether or not the plain to keep iOS 7/8 support has changed? If not, would it be possible to change the iOS Deployment Target setting to iOS 7.0 instead of 8.3? Every time I have to reinstall my node modules, I have to go in and change it in order to be able to build my project.

**Comment by morenoh149** [comment]
@bdbergeron what would have to change in the source to remove this annoyance? I see 7.0.1 listed here https://github.com/rt2zz/react-native-contacts/blob/master/ios/RCTContacts.xcodeproj/project.pbxproj#L99

**Comment by bdbergeron** [comment]
(Replied via email, but for some reason this didn't post. Posting again.)

That line specifies which version of Xcode initially created the project. The lines that needs to change are those with IPHONEOS_DEPLOYMENT_TARGET. I also noticed that current file has different values set for the project (9.0) vs. the target (8.3). I'll submit a PR cleaning this up.
