### ISSUE TITLE
Error on Build - package androidx.anottation

### ISSUE THREAD

**Issue by rafaumlemos** [rt2zz/react-native-contacts#400]
Hi guys.
I follow the installation guide and i'm with this error on build:

https://imgur.com/a/nOphw4M

I was checking some issues and i found that's similar with this one:
https://github.com/rt2zz/react-native-contacts/issues/395

Thanks for helping.

**Comment by rafaumlemos** [comment]
If i change all androidx imports to not androidx, like:

// import androidx.annotation.NonNull;
// import androidx.core.app.ActivityCompat;
import android.support.annotation.NonNull;
import android.support.v4.app.ActivityCompat;

The error changes to:

https://imgur.com/a/u8fzkuB

**Comment by rafaumlemos** [comment]
I solved it.

I change all androidx import, as i said here: 

> If i change all androidx imports to not androidx, like:
> 
> // import androidx.annotation.NonNull;
> // import androidx.core.app.ActivityCompat;
> import android.support.annotation.NonNull;
> import android.support.v4.app.ActivityCompat;
> 
> The error changes to:
> 
> https://imgur.com/a/u8fzkuB


Then i run: react-native link

Thats it.

**Comment by morenoh149** [comment]
in the future please share errors as text so others can find via search

**Comment by mikehardy** [comment]
Hi there! The whole react-native community will be [struggling with the AndroidX transition for a while](https://github.com/react-native-community/discussions-and-proposals/issues/129). 

The community came up with a tool called jetifier that offers forwards compatibility from non-AndroidX apps to libraries (like this one) that have implemented AndroidX, by ["reverse-jetifying" the source with a call to `npx jetify -r`](https://github.com/mikehardy/jetifier#to-reverse-jetify--convert-node_modules-dependencies-to-support-libraries) so you can use the AndroidX version of the library in your non-AndroidX app, until you migrate.

I've tested it on this module and it appears to work (I use react-native-contacts in my app, I'm not just the jetifier maintainer).

I encourage you to migrate to AndroidX, but until then this can help.

When you do migrate to AndroidX you have the opposite problem with other libraries at which point you'd use [jetifier in the forward direction](https://github.com/mikehardy/jetifier#to-jetify--convert-node_modules-dependencies-to-androidx) with a call to `npx jetify`.

Please help spread the word so your fellow developers don't get stuck - app development is hard enough. Cheers!
