### ISSUE TITLE
issue with installing

### ISSUE THREAD

**Issue by rshahboon1** [rt2zz/react-native-contacts#402]
I am trying to solve this issue for 3 days , please any one can help 

details when running `react-native run-android`

`* What went wrong:
Execution failed for task ':react-native-contacts:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
19 actionable tasks: 1 executed, 18 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: ./gradlew app:installDebug. Run CLI with --verbose flag for more details.`

**Comment by morenoh149** [comment]
please run gradle with the`--warning-mode all` flag so we can review the specific deprecations. It's probably something like `./gradlew app:installDebug --warning-mode all` in the `android` folder.

**Comment by williamgurzoni** [comment]
I'm not a specialist, but it seams a problem with Androidx migration... This migration will be mandatory?

**Comment by morenoh149** [comment]
@williamgurzoni yes. Read https://medium.com/@yathousen/the-day-google-decided-to-shake-the-react-native-community-4ba5cdd33388 to learn more about the situation.

**Comment by jpomaza** [comment]
Followed those steps but I still getting the same error. Any other Idea?

**Comment by jpomaza** [comment]
> ./gradlew app:installDebug --warning-mode all

@morenoh149 the only message I get is:

> Task :react-native-contacts:generateDebugRFile UP-TO-DATE
Changing the value for a property with a final value has been deprecated. This will fail with an error in Gradle 6.0.

**Comment by acoulon99** [comment]
I'm also encountering something similar. Here's the error output I'm experiencing. I'm using version _4.0.2_ of _react-native-contacts_

When I run `./gradlew app:installDebug --warning-mode all` I received the same information @morenoh149 did.

```
> Task :react-native-contacts:compileDebugJavaWithJavac FAILED
/Users/puma/wigo-mobile/node_modules/react-native-contacts/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java:50: error: ContactsManager is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
public class ContactsManager extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
/Users/puma/wigo-mobile/node_modules/react-native-contacts/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java:1053: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/puma/wigo-mobile/node_modules/react-native-contacts/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java:1099: error: method does not override or implement a method from a supertype
    @Override
    ^
3 errors
```

**Comment by Girgetto** [comment]
I had the same error, I was using:

**versions:**
```
"react-native": "0.57.8",
"react-native-contacts": "^5.0.2",
```

The `build.gradle` with:
```
compileSdkVersion = 27
targetSdkVersion = 27
supportLibVersion = "27.1.1"
```

In `react-native-contacts: 5.0.2` use version `28` in `build.gradle`, so **I had to downgrade** to version `4.0.0` of `react-native-contacts` that use version `27`, and now it's working in `Android` and `ios`

**Working versions:**
```
"react-native": "0.57.8",
"react-native-contacts": "^4.0.0",
```

**Comment by morenoh149** [comment]
interesting. Moving forward most projects should use at least android 28. @Girgetto is there any reason you didn't upgrade your grade to 28 instead of downgrading rnc to 4.0.2?

**Comment by Girgetto** [comment]
@morenoh149 I tried to upgrade to 28 but it didn't work

**Comment by morenoh149** [comment]
solved at https://github.com/rt2zz/react-native-contacts/issues/395#issuecomment-506326188
