### ISSUE TITLE
Cannot be installed on AndroidX -- Native Module Contacts tried to override ContactsManager

### ISSUE THREAD

**Issue by bobber205** [rt2zz/react-native-contacts#420]
![Android Emulator - Pixel_2_API_27:5554 2019-08-02 13-04-31](https://user-images.githubusercontent.com/5841107/62395765-1491e080-b526-11e9-9afa-c5e1272f2fa1.png)

Will update this ticket if I find a solution.

My `MainApplication.java`

```java
   @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:

      packages.add(new AppCenterReactNativePushPackage(this.getApplication()));
      packages.add(new AppCenterReactNativeCrashesPackage(this.getApplication(), getResources().getString(R.string.appCenterCrashes_whenToSendCrashes)));
      packages.add(new AppCenterReactNativeAnalyticsPackage(this.getApplication(), getResources().getString(R.string.appCenterAnalytics_whenToEnableAnalytics)));
      packages.add(new AppCenterReactNativePackage(this.getApplication()));
      packages.add(new ReactNativeContacts());
      return packages;
    }
```

**Comment by morenoh149** [comment]
gosh this is so odd. We even had the author of Jetifier update this repo for androidx. LMK if you figure anything out. There's more info in other issues (closed ones too).

**Comment by bobber205** [comment]
Agreed. I am triple checking to make sure it isn't user error at the moment.

**Comment by bobber205** [comment]
I wonder if it could be related to my usage of `npx jetify` during the postinstall step?

**Comment by bobber205** [comment]
@morenoh149 I did some searching but I can't find any issues closed or open that seem relevant to this issue -- do you mind pointing me in the right direction?

**Comment by bobber205** [comment]
ok -- I was using React 0.60.x and auto linking -- turns out the auto linking was adding this package (like it should have). So I didn't need the new ReactNativeContacts() line at all.

**Comment by morenoh149** [comment]
this was the author of Jetifier confirming this repo is androidx ready. https://github.com/rt2zz/react-native-contacts/issues/395#issuecomment-506326188
