### ISSUE TITLE
Social Profiles are not included when invoking the getAll method

### ISSUE THREAD

**Issue by TylerIlunga** [rt2zz/react-native-contacts#421]
I tried to modify "RCTContacts.m" and add "CNSocialProfileKey" to the "retrieveContactsFromAddressBook" method but that did not seem to work

**Comment by TylerIlunga** [comment]
Had to write additional code with RCTContacts.m but I got it!

**Comment by KristineTrona** [comment]
@TylerIlunga can you share the additional code you wrote to get this working?

**Comment by TylerIlunga** [comment]
@KristineTrona Code can be found [here](https://github.com/morenoh149/react-native-contacts/pull/422/commits)!
Let me know if you're still having any issues with getting it to work on your end

**Comment by jensonstack** [comment]
@KristineTrona can you please share the code to access social profiles
