### ISSUE TITLE
I never seen a module worst than this

### ISSUE THREAD

**Issue by narenderv7** [rt2zz/react-native-contacts#423]
Is there any better module than this?

I followed every step here https://github.com/rt2zz/react-native-contacts#installation

Every time imports return undefined.

![image](https://user-images.githubusercontent.com/29437633/63314653-03b6dc80-c326-11e9-8c29-d02f9e99cb7c.png)

![image](https://user-images.githubusercontent.com/29437633/63314675-10d3cb80-c326-11e9-88b1-653688d6a6a0.png)

![image](https://user-images.githubusercontent.com/29437633/63314689-1e895100-c326-11e9-9ad2-02054406a874.png)

![image](https://user-images.githubusercontent.com/29437633/63314705-2a751300-c326-11e9-9511-d5d54389d92a.png)

![image](https://user-images.githubusercontent.com/29437633/63314718-3234b780-c326-11e9-9bf4-8ffb550afa87.png)

**Comment by BilalBudhani** [comment]
@narenderv7 dude have some compassion & empathy for maintainers. If you're having a bad day doesn't mean you will spill your frustration wherever you feel like.

**Comment by kuldeepkeshwar** [comment]
@narenderv7 How about 👇
If this(module) isn’t working for you, why don’t you create a pull request with changes that solve the problem or improve the experience 😊

**Comment by Taym95** [comment]
You know the vibes!

![Screenshot 2019-08-20 at 14 27 36](https://user-images.githubusercontent.com/14943106/63347136-cdde1c00-c356-11e9-89f8-9d2686a186fa.png)

**Comment by narenderv7** [comment]
@BilalBudhani It's Not Just a day Bruh, I've wasted 7 days. How stupid this, instead I should've written my own module. :joy: :joy: :joy: :joy: :joy:

**Comment by morenoh149** [comment]
No one pays to maintain this. This is oss.

**Comment by narenderv7** [comment]
@morenoh149 I get it, Is there is a way to delete this issue?
