### ISSUE TITLE
Contacts.getContactById throws exception on IOS when passing recordID

### ISSUE THREAD

**Issue by wimvdb** [rt2zz/react-native-contacts#426]
When invoking Contacts.getContactById on IOS

I get this exception:

Exception '*** -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: recordID)' was thrown while invoking getContactById on target Contacts with params (
    "E1CD3D08-76A9-4D11-A1E0-6CF9D9066280:ABPerson",
    4473
)

The code I'm using:

```javascript
const getContactById = (recordID, resolve, reject) => {
    const getContactByIdCallback = (err, nativeContact) => {
        if (err) {
            reject(err);
        }
        resolve(nativeContact);
    };
    Contacts.getContactById(recordID, getContactByIdCallback);
}
```
What am I doing wrong?

**Comment by morenoh149** [comment]
recordID seems undefined on line `Contacts.getContactById(recordID, getContactByIdCallback);
`

**Comment by wimvdb** [comment]
Hey,

Thanks for the response. recordId is passed in as an argument and it's value is set to "E1CD3D08-76A9-4D11-A1E0-6CF9D9066280:ABPerson" as printed in the error message.

The exception is thrown when there is no contact with a corresponding recordID. According to the documentation it should return null when this happens.

**Comment by wimvdb** [comment]
Thanks for the response. 

The recordID is passed into the function as an argument and was set to "E1CD3D08-76A9-4D11-A1E0-6CF9D9066280:ABPerson" as shown in the error message.

I did some more investigating and the steps to reproduce are:

Get the recordID from an existing contact.
Delete the contact with this recordID in the native contact app.
Execute Contacts.getContactById with the recordID from the contact that has been deleted.

**Comment by morenoh149** [comment]
that is not surprising behavior. You are trying to read a record that does not exist.

**Comment by wimvdb** [comment]
According to the documentation it's supposed to return null if the record does not exist.

> getContactById(contactId, callback) - returns contact with defined contactId (or null if it doesn't exist)

In any case it seems like a nasty bug that should be handled gracefully instead of crashing the application.

I was able to work around it (not very efficiently) like so:

````javascript
const getContactById = (recordID, resolve, reject) => {
    const getContactByIdCallback = (err, nativeContacts) => {
        if (err) {
            reject(err);
        }
        const result = nativeContacts.find(nc => nc.recordID === recordID);
        if (result) {
            resolve(result);
        } else {
            reject('Contact not found');
        }
    };
    Contacts.getAllWithoutPhotos(getContactByIdCallback);
};
````

It would be great if it could be fixed :)

**Comment by morenoh149** [comment]
ah didn't know the docs said that. Please submit a PR for that and I'll merge it.

**Comment by arnaudambro** [comment]
Same here, I have this error: 
`Exception '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]' was thrown while invoking getContactById on target Contacts with params (
    "7BE82C42-D6E5-449D-8B13-3A5057D8FE06"`

Thing is, the `recordID` I am really looking for is not `7BE82C42-D6E5-449D-8B13-3A5057D8FE06` but `7BE82C42-D6E5-449D-8B13-3A5057D8FE06:`**`ABPerson`**, and when I `getContactById` with this ID, it returns null... so I am a bit lost !

**Comment by benanderman** [comment]
We've been seeing a similar crash (but have no reproduced locally), but with `getAll`; it seems like it may be the same issue, just in a different place?
```
RCTFatalException: Exception '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]' was thrown while invoking getAll on target Contacts with params (
    69707
)
```

**Comment by morenoh149** [comment]
@benanderman not sure. Want to open a fresh issue?

**Comment by zingerj** [comment]
Just tested @wimvdb's fix in #430 and I am still getting an exception thrown on iOS when trying to `getContactById` on a record that doesn't exist. On version `5.1.0` I'm getting the following output:
```
ExceptionsManager.js:126 Exception '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]' was thrown while invoking getContactById on target Contacts with params (
    "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
    6031
)
```
Does anyone know what's causing this? Seems like `if(!contact) return nil;` should be catching this case...

**Comment by morenoh149** [comment]
not if the error is within the bridge itself

**Comment by zingerj** [comment]
What does that mean? Sorry, I'm new to iOS and native packages. This issue continues to crash my app. What would it take to handle the case where a contact of a specific ID is missing more gracefully?

**Comment by morenoh149** [comment]
I'm not sure. Getting an objective-c engineer to take a look would be a good start. Then we can decide whether to fix it in the js api or within the bridge (the bridge is the objective-c code).

**Comment by zingerj** [comment]
Can anyone help with this? It's still causing issues for my app and sounds like @danwhite-ipc ran into the same thing.
