### ISSUE TITLE
Undefined is not an object ('_reactNativeContacts.Contacts.getAll') in android

### ISSUE THREAD

**Issue by achintyaha** [rt2zz/react-native-contacts#427]
I have done all the required things by following the installation process from **react-native-contacts** main page. 
output of **react-native link react-native-contacts**

info iOS module "react-native-contacts" is already linked
info Android module "react-native-contacts" is already linked

Even if I unlink it, I am getting the same error.

I am using below setup:
react-native-cli: 2.0.1
react-native: 0.60.5

How to resolve this issue?

**Comment by todorone** [comment]
@achintyaha Starting from 0.60 RN does not require linking, it should work out of the box with no linking...

**Comment by morenoh149** [comment]
@todorone should we remove the linking steps from the readme?

**Comment by todorone** [comment]
@morenoh149 I guess it's better to write something like:
- RN 0.60+ requires no linking, you are done with the installation
- RN <0.60 link library on iOS / Android by: ...
