### ISSUE TITLE
getAllWithoutPhotos doesn't return anything Ios 13

### ISSUE THREAD

**Issue by Grivel-l** [rt2zz/react-native-contacts#439]
`getAllWithoutPhotos` return no error and a an empty array on Ios 13.
Tested on an iPhone 8 Plus 13.0

**Comment by Baskerville42** [comment]
The same situation for the `getAll` method. No errors, and empty array in the callback.
version: 2.2.5,

**Comment by Grivel-l** [comment]
My bad, it has been fixed in the latest package update (5.0.4)
