### ISSUE TITLE
the library is ready for iOS 13?

### ISSUE THREAD

**Issue by franjorub** [rt2zz/react-native-contacts#440]
in iOS 12 the library works perfect without any issues, this time never return the contacts we are using the version 4.x with RN 0.59

**Comment by morenoh149** [comment]
probably not, if things have changed in 13 we need a ticket to make those changes.

**Comment by Grivel-l** [comment]
There is no problem on Ios 13 with `5.0.4` #439

**Comment by luism3861** [comment]
5.0.4 i'ts very good
