### ISSUE TITLE
.getAll() returns empty array

### ISSUE THREAD

**Issue by danieltov** [rt2zz/react-native-contacts#445]
I've been stuck on this one for hours. The `getAll()` method is returning an empty array on my iOS 13 test device with 143 contacts running RN 0.59.

Here is my code:

```javascript
import Contacts from 'react-native-contacts'
...

componentDidMount() {
    this.getContacts()
}

async getContacts() {
    let reactContacts = await this.reactContacts()
    ...
}

async reactContacts() {
    let promise = new Promise((resolve, reject) => {
      Contacts.getAll((err, contacts) => {
        if (err) {
          reject(err)
        } else {
          resolve(contacts) // this returns: []
        }
      })
    })
    return await promise
  }
```

Because it's not returning any errors, it's really hard to figure out why this isn't working! Especially because it was working on earlier builds of my app. Any insight would be greatly appreciated!

**Comment by fxhrgco** [comment]
Same occurring here! With RN 0.59.
error: null, contacts: []

**Comment by Jobeso** [comment]
Faced the same issue with 0.59. Upgrading the library to 5.0.4 fixes the problem. Could be related to the "note" field, the native code returns CNInvalidRecords.
<img width="425" alt="Screenshot 2019-10-14 at 00 07 01" src="https://user-images.githubusercontent.com/22718514/66742746-aa2be380-ee78-11e9-91db-e95e3b0dfc06.png">

**Comment by danieltov** [comment]
So 5.0.4 works on <RN 0.60? I’ll give it a try!

**Comment by danieltov** [comment]
It worked! Thanks a lot!

**Comment by morenoh149** [comment]
yep, breaking changes between rn 59 and 60. use older or later depending on which side you are on.
