### ISSUE TITLE
#App crashes when Contact.getAll function is called in android

### ISSUE THREAD

**Issue by ArjjunM** [rt2zz/react-native-contacts#451]
**Version**
RN : 0.59
RNC: 4.0.0

App get crashed when getAll function is called without showing any error, suddenly crash's the app.

Thank you

**Comment by jonsey247** [comment]
Hello, same for me.
Version
RN : 0.61.2
RNC: 5.0.4

**Comment by ArjjunM** [comment]
any solution ??

**Comment by mayankmittal242** [comment]
Give permission to read contact 

import { PermissionsAndroid } from "react-native"; 

 PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.READ_CONTACTS, {
      title: "Contacts",
      message: "This app would like to view your contacts."
    }).then(() => {
      Contacts.getAll((err, contacts) => {
        if (err === "denied") {
          console.log("permissionDenied");
          // error
        } else {
          console.log(contacts);
          // contacts returned in Array
        }
      });
    });
  }

**Comment by jonsey247** [comment]
Going to try the code above but after some reading found it’s a permission issue (causes the app the crash)

**Comment by ArjjunM** [comment]
Hi @mayankmittal242 

It worked man : )
Thanks man

Hi @jonsey247 
Please try the given code 

Thank you all for the help, closing the issue

**Comment by morenoh149** [comment]
read the readme. It'll help your career!
