### ISSUE TITLE
NPM version issue

### ISSUE THREAD

**Issue by andrewanderson58** [rt2zz/react-native-contacts#453]
It appears the library was published 7 days ago with an older version.
![Screen Shot 2019-11-21 at 10 02 13 AM](https://user-images.githubusercontent.com/55415304/69354665-16eb8800-0c46-11ea-93af-2c41be855fc4.png)

**Comment by morenoh149** [comment]
That is a back port of a bugifix for users of rn < 60. Some ppl cannot use modern rn due to the androidX migration. If you are on rn 60+ use the 5.x.x series.
