### ISSUE TITLE
About new android version

### ISSUE THREAD

**Issue by joaodematejr** [rt2zz/react-native-contacts#471]
Hello, I was using the version of this library 5.0.5 and I decided to upgrade to the latest version that at the moment I'm writing this is 5.0.6, but it stopped working on the android version, I looked that you removed the permission to read the contacts, is there any reason for this? after I went to the node_modules / react-native-contacts / android /.../ AndroidManifest folder and put the permission back on.

**Comment by morenoh149** [comment]
causes request for permission when the app might not need it https://github.com/rt2zz/react-native-contacts/pull/466 consider using the latest android apis.
