### ISSUE TITLE
Whether it have option to show the list of alphabets at right of the screen to filter the contacts 

### ISSUE THREAD

**Issue by nihp** [rt2zz/react-native-contacts#485]
Whether it has the option to show the list of alphabets at the right of the screen to filter the contacts

**Comment by morenoh149** [comment]
no the library does not have that option.

**Comment by nihp** [comment]
Shall you add this in a feature requests?

**Comment by morenoh149** [comment]
You can open a new issue to submit a feature request. If you can implement it and submit a PR even better.
