### ISSUE TITLE
Don't Migrate to Contacts!

### ISSUE THREAD

**Issue by MarkEstefanos** [rt2zz/react-native-contacts#52]
Or at least if you do, maintain the AddressBook implementation for iOS 7 and iOS 8 support. Thanks for your good work!

**Comment by morenoh149** [comment]
why not

**Comment by MarkEstefanos** [comment]
Contacts in iOS is only supported in iOS 9. 16% of users are still on iOS 8, so it's worthwhile to write backwards compatible code.

**Comment by npomfret** [comment]
We want to migrate soon because we think the new api fixes some issues.  I understand adoption of 9 is very high now:

http://razorianfly.com/2016/04/22/ios-9-adoption-is-nearly-at-100-stats/
