### ISSUE TITLE
Adding RX support

### ISSUE THREAD

**Issue by JeanLebrument** [rt2zz/react-native-contacts#6]
Hello,

I'm using this package on a project but I added RxJS support to the methods of this package to be able to return an observer object instead of passing completionBlock in parameter.

Would you be interested by a pull request to integrate this features in your package or should I create my own package `react-native-contacts-rx` to add the support of RxJS?

Best,
Jean

**Comment by rt2zz** [comment]
Yes, rx is too heavy of a dependency to make it part of the main package. However having a seperate react-native-contacts-rx module would be great.

Let me know if any api changes are needed to make this work. Also after you publish it, we should put a link to it in the readme.

**Comment by JeanLebrument** [comment]
Good. I will create a separate package then! You don't need to change anything to your API. I will tell when it will be released.

**Comment by JeanLebrument** [comment]
After few discussions with colleagues, I wonder if creating another package only to add the support of Rx would be overkill. I only extends the contact package by adding `rx_` prefixed methods for each method that takes a `completionHandler` in parameter. (Gist available here: https://gist.github.com/JeanLebrument/304ba2bd8547a6ed4e7f).

My concern is: Is this a good "guideline" to create another package to add the Rx support to an existing package? Or would it be smarter to add an optional support to the main package? (I created an other Gist for the optional support: https://gist.github.com/JeanLebrument/6dc373647b44fb4def7a)
I would like to have your opinion on this question.

**Comment by rt2zz** [comment]
I am all about node style small modules and definitely do not think they are overkill. Along those lines I would love if every package had a `[package-name]-rx` counterpart, which makes opting in as a consumer dead simple.

Another issue is that not all packaging systems (including I believe the react-native one) respect try/catch since they typically do static analysis to create the bundles.

**Comment by JeanLebrument** [comment]
Thanks for your feedback, I will do this then.

**Comment by JeanLebrument** [comment]
Here we go -> https://github.com/JeanLebrument/react-native-contacts-rx
