### ISSUE TITLE
Built for newer iOS version (9.0) than being linked (8.0)

### ISSUE THREAD

**Issue by niftylettuce** [rt2zz/react-native-contacts#61]
There is an inconsistent `IPHONEOS_DEPLOYMENT_TARGET` in https://github.com/rt2zz/react-native-contacts/blob/master/ios/RCTContacts.xcodeproj/project.pbxproj.  Is it 8.0, 8.3, or 9.0?

**Comment by npomfret** [comment]
Same, I'm getting this error:

`object file (/Users/nickpomfret/Library/Developer/Xcode/DerivedData/pomochat-cvkhcsdfxgmgokbegzcqhdxmcngh/Build/Products/Debug-iphonesimulator/libRCTContacts.a(RCTContacts.o)) was built for newer iOS version (9.0) than being linked (7.0)
`

Would it be possible to link it to IOS 7?

**Comment by morenoh149** [comment]
would this fix it? https://github.com/rt2zz/react-native-contacts/pull/60

**Comment by npomfret** [comment]
I'd like to say yet, but I'm no expert on IOS

**Comment by npomfret** [comment]
We're going to move to iOS 9 only soon as the new API fixes some issues.
