### ISSUE TITLE
How about just open the address book?

### ISSUE THREAD

**Issue by duranmla** [rt2zz/react-native-contacts#62]
I was looking forward to be able to open the address book (supporting API level 18) and select a contact. Seems like it is something that we cannot do with this module right?

**Comment by rt2zz** [comment]
This is conceivably possible with https://developer.apple.com/library/ios/documentation/AddressBookUI/Reference/ABPeoplePickerNavigationController_Class/ but currently react-native-contacts does not implement such a feature. PR's welcome!

**Comment by morenoh149** [comment]
The point of the module is to get phone contact info into an RN app. What you're describing is like a modal or screen transition. If you think it would make sense to do that please submit a PR.

**Comment by Proyoyo** [comment]
@duranmla 
We've made something that you described in this library. The library's functionalities are currently very basic but any PR is welcomed:
https://github.com/LynxITDigital/react-native-contacts-wrapper

**Comment by morenoh149** [comment]
closing as solved. wontfix.

**Comment by jeremyfrancis** [comment]
> @duranmla
> We've made something that you described in this library. The library's functionalities are currently very basic but any PR is welcomed:
> https://github.com/LynxITDigital/react-native-contacts-wrapper

Cool, but this doesn't return the recordID and that is pretty important.
