### ISSUE TITLE
A little suggestion

### ISSUE THREAD

**Issue by zhongjie-chen** [rt2zz/react-native-contacts#65]
![qq 20160615190550](https://cloud.githubusercontent.com/assets/14540231/16077553/343db226-332c-11e6-8380-85021734057e.png)
This attribute will have better returns ""

**Comment by zhongjie-chen** [comment]
middleName

**Comment by morenoh149** [comment]
you're suggesting that middleName should return `""` if there is no middle name.

**Comment by rt2zz** [comment]
in js its more typical to see null over empty string. The fact that thumbnailPath is an empty string is more an artifact of the way the original implementation was written. @zhongjie-chen can you clarify why you prefer empty string?

**Comment by morenoh149** [comment]
closing as nonissue.
