### ISSUE TITLE
Instant permissionDenied

### ISSUE THREAD

**Issue by dubbelnisse** [rt2zz/react-native-contacts#68]
I'm getting the permissionDenied when doing getAll on iOS, works great on Andriod.

Error message:
`{ type: 'permissionDenied' }`

This is the code:

```
Contacts.getAll((err, contacts) => {
      if(err && err.type === 'permissionDenied'){
        dispatch(receiveContactsError())
      } else {
        dispatch(receiveContacts(contacts))
     }
})
```

Is this an know issue?

**Comment by morenoh149** [comment]
First report.

**Comment by dubbelnisse** [comment]
Could it be iOS or react-native version problems?

**Comment by morenoh149** [comment]
not likely. But I just merged a PR and published a new npm version so you should test that out.

**Comment by dubbelnisse** [comment]
Did't work with new version. I've tried `checkPermission ` and `requestPermission ` but it goes straight to denied anyway.

**Comment by rt2zz** [comment]
@dubbelnisse it sounds like you denied the contacts permission at some point in the past. If this is the case you will need to manually toggle it back on in the settings app.

**Comment by gp3gp3gp3** [comment]
I have the opposite problem.  Works fine in the phone simulator for xcode, but is denied instantly on android.

**Comment by ramancodians** [comment]
I'm having the same issue. 
```
Contacts.checkPermission( (err, permission) => {
        console.log(permission);
        if(permission === 'denied'){
          Contacts.requestPermission((error,permission)=>{
            console.log(error,permission)
          });
        }
  });
```
It never requests for Contacts and denies straight away.  If I try `getAll()`, it crashes the app.

**Comment by npomfret** [comment]
If you're having an issue with iOS could you try my fork out https://github.com/npomfret/react-native-contacts/commits/master.  Sorry but I've not upgraded to RN-40+ yet so the headers may need to be changed if you have.

I'm made every method check the _health_ of the contacts store object before using it, and return an auth code style error if it's not healthy.  I've also upgraded the remaining methods that were using the old _AB_ API to use the new one.

Note that the _getAll_ method no longer lazily requests permissions (so it behaves in a consistent manner to the others).

**Comment by npomfret** [comment]
If you're having an issue with iOS could you try my fork out https://github.com/npomfret/react-native-contacts/commits/master. Sorry but I've not upgraded to RN-40+ yet so the headers may need to be changed if you have.

I'm made every method check the health of the contacts store object before using it, and return an auth code style error if it's not healthy. I've also upgraded the remaining methods that were using the old AB API to use the new one.

Note that the getAll method no longer lazily requests permissions (so it behaves in a consistent manner to the others).

**Comment by nitish24p** [comment]
Im getting the same on android..

**Comment by morenoh149** [comment]
We now recommend using https://facebook.github.io/react-native/docs/permissionsandroid.html please report back if that works.
