### ISSUE TITLE
Thumbnails causes whole app to crash unexpectedly

### ISSUE THREAD

**Issue by zevmo** [rt2zz/react-native-contacts#72]
On one of our devices, we had a huge address book (approx 2500 contacts), and our app wasn't able to read that at all, always crashing inside getAll(). When we commented out https://github.com/rt2zz/react-native-contacts/blob/master/ios/RCTContacts/RCTContacts.m#L162 line, it started to work. We haven't investigated it further yet.

**Comment by tomauty** [comment]
Has to do with this method I believe:

```objective-c
-(NSString *) getABPersonThumbnailFilepath:(ABRecordRef) person
{
  if (ABPersonHasImageData(person)){
    CFDataRef photoDataRef = ABPersonCopyImageDataWithFormat(person, kABPersonImageFormatThumbnail);
    if(!photoDataRef){
      return @"";
    }

    NSData* data = (__bridge_transfer NSData*)photoDataRef;
    NSString* tempPath = [NSTemporaryDirectory()stringByStandardizingPath];
    NSError* err = nil;
    NSString* tempfilePath = [NSString stringWithFormat:@"%@/thumbimage_XXXXX", tempPath];
    char template[tempfilePath.length + 1];
    strcpy(template, [tempfilePath cStringUsingEncoding:NSASCIIStringEncoding]);
    mkstemp(template);
    tempfilePath = [[NSFileManager defaultManager]
    stringWithFileSystemRepresentation:template
    length:strlen(template)];
    
    tempfilePath = [tempfilePath stringByAppendingString:@".png"];

    [data writeToFile:tempfilePath options:NSAtomicWrite error:&err];
    CFRelease(photoDataRef);
    if(!err){
      return tempfilePath;
    }
  }
  return @"";
}
```

Looks like we're writing a file each time the contact is fetched. I wonder if there is a workaround, given iOS app constraints regarding containerization.

**Comment by npomfret** [comment]
Yes, this is a known bug.  I'm in the process of testing a work around.  You can help if you like, point your code at my fork: 

    "react-native-contacts": "git@github.com:npomfret/react-native-contacts.git",
