### ISSUE TITLE
Problem with GetAll

### ISSUE THREAD

**Issue by varunkhurana999** [rt2zz/react-native-contacts#79]
Hi,
I'm pretty new to Native and have been trying to solve this problem with my code forever. My file seems to be able to read the (react-native-contacts) file but when I use the GetAll function Error, I get the following error: 

> "undefined is not an object (evaluating "Contacts.getAll")

I've attached a copy of my code for the relevant function. If y'all could let me know what I'm doing wrong would be great!
![image](https://cloud.githubusercontent.com/assets/20623266/17089187/ca17b754-51d8-11e6-9a7c-00e89b539bcb.png)

**Comment by morenoh149** [comment]
text trumps images so in the future please paste your code instead.

Could you share the stacktrace and error please.

**Comment by jtewright** [comment]
@varunkhurana999 I expect your problem is with `Contacts`, not `getAll`. You may need to do more installation steps: https://github.com/rt2zz/react-native-contacts#getting-started

**Comment by morenoh149** [comment]
closing as stale

**Comment by iraycd** [comment]
```
 fatal error: could not build module 'AddressBook'
#import <AddressBook/AddressBook.h>
```
