### ISSUE TITLE
Rerequest permissions (iOS)

### ISSUE THREAD

**Issue by morenoh149** [rt2zz/react-native-contacts#8]
Is there any way to have the app rerequest the user for access to the contacts? If not I can document that behavior.

**Comment by JeanLebrument** [comment]
On iOS you can check and/or request the user's permission to access to his contacts: https://github.com/rt2zz/react-native-contacts#permissions-methods-ios-only-optional

**Comment by morenoh149** [comment]
@JeanLebrument I'm sorry Jean. That does not answer the issue. Can an app re-request permission after a denial?
I believe it can't. If so I can document it why (ios limitation, whatever).

**Comment by rt2zz** [comment]
iOS will not re-prompt the user. If AddressBook access is critical to the application, the best you can do is prompt the user with instructions for how to enable contacts. i.e. `Go to your settings and enable...`

**Comment by JeanLebrument** [comment]
My bad, I rade request instead of rerequest. I reopen the issue until you found an answer.

**Comment by bsy** [comment]
I'm running into an issue where even if uninstall the app on my device/simulator, I don't get the permissions dialog, and always getting `permissionDenied` back from `Contacts.getAll`.   Also, I don't see Contacts being denied when I look at Settings -> [app name] ... running iOS 9.3.1.   Any ideas on why?

**Comment by bsy** [comment]
I'm wondering if this is related to iOS 9.3.x, because this was working just fine in a commit in my code base on March 17th.

**Comment by bsy** [comment]
Nevermind on my 9.3.x theory, just installed the iOS 9.2 simulator and still getting the issue
