### ISSUE TITLE
Add postal address(es) to contacts response [Android]

### ISSUE THREAD

**Issue by morenoh149** [rt2zz/react-native-contacts#82]
We need a matching PR for https://github.com/rt2zz/react-native-contacts/pull/81

**Comment by deepmehtait** [comment]
@morenoh149  Postal address has been implemented in android?

**Comment by morenoh149** [comment]
@deepmehtait has it? I don't believe so.

**Comment by npomfret** [comment]
I believe this is done - can we close?

**Comment by morenoh149** [comment]
@npomfret feel free to close in the future. It can always be reopened.
