### ISSUE TITLE
Contacts do not get deallocated, I have noticed app storage on device increase significantly with each pull

### ISSUE THREAD

**Issue by antonellil** [rt2zz/react-native-contacts#86]
First, awesome job on this module, it is very helpful! For reference I am using this only for iOS right now. This is an issue and what I think would be a solution, but not sure how to write it in swift.

I have noticed while using the module that it seems to increase the size of my app on my iPhone's storage by what I am guessing is the size of the contacts list, every time that I call getAll (which is just on app start).

I am guessing this is because the contacts array created here (https://github.com/rt2zz/react-native-contacts/blob/master/ios/RCTContacts/RCTContacts.m#L70) is not being deallocated. I have never written swift but a quick search shows that instead of `init` on that line, it would be `autorelease` instead, and at some point `[contacts removeAllObjects]` would be called. Again, I do not know where that remove all objects could be called because the array has to be returned first.

Any help on this would be awesome, thanks!

**Comment by morenoh149** [comment]
To be clear the ios code is all objective-C. I may write future features in swift though.

**Comment by antonellil** [comment]
@morenoh149 ah I see sorry about that. Does the proposed issue make sense though?

**Comment by morenoh149** [comment]
I don't see `autorelease` as a valid argument into the `NSMutableArray` declaration https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSMutableArray_Class/index.html#//apple_ref/occ/instm/NSMutableArray/initWithCapacity:

Mind forking the repo and testing it locally? https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by antonellil** [comment]
Yes I will fork and test and report back

**Comment by npomfret** [comment]
I wonder if its the icons files?  Does you address book contain lots of contacts with pictures?  When I say lots I mean thousands?

**Comment by coderdave** [comment]
I'm glad I found this issue because I was wondering why some users were reporting that the app would become unresponsive after importing about 10 or so contacts.

Now I just bypass the `getAll()` call if the contacts are already loaded in state and the app is fine. The only downside of course is that it's not retrieving the most updated list of contacts.

**Comment by coderdave** [comment]
So what's the proper way to deallocate the contacts array? I'm seeing my app not respond after calling `getAll()` about 10 or so times.

**Comment by morenoh149** [comment]
@coderdave there is an outstanding PR https://github.com/rt2zz/react-native-contacts/pull/118 you could help test.

@npomfret submitted and merged a fix for the file handle leaks at https://github.com/rt2zz/react-native-contacts/pull/99 @coderdave are you using version >= 0.5.2 ?

**Comment by coderdave** [comment]
@morenoh149 I upgraded to version `0.6.0` and it looks like it's _better_, but after about 60 calls to `getAll()`, the app becomes unresponsive.

I'll have to test the PR next.

**Comment by npomfret** [comment]
Which OS?

**Comment by npomfret** [comment]
Can we close this?  The iOS implementation has been completely re-written.  I think it doesn't suffer from this problem any more.
