### ISSUE TITLE
The Address Book framework is deprecated in iOS 9.

### ISSUE THREAD

**Issue by joonhocho** [rt2zz/react-native-contacts#87]
According to https://developer.apple.com/library/ios/documentation/AddressBook/Reference/AddressBook_iPhoneOS_Framework/index.html#//apple_ref/doc/uid/TP40007212.

> IMPORTANT
> 
> The Address Book framework is deprecated in iOS 9. Use the APIs defined in the Contacts framework instead. To learn more, see Contacts Framework Reference.

**Comment by zevmo** [comment]
+1

**Comment by shahen94** [comment]
+1

**Comment by Jarred-Sumner** [comment]
+1

**Comment by sscaff1** [comment]
+1

**Comment by morenoh149** [comment]
https://help.github.com/articles/subscribing-to-conversations/

**Comment by npomfret** [comment]
Anyone on here familiar with the new API?

**Comment by npomfret** [comment]
I've had a go at updating the iOS code to use the new iOS contacts api in my fork https://github.com/npomfret/react-native-contacts.  For now I've only tackled the read-only methods.

@krishangupta @morenoh149 @berkaey @antonellil @ChrisPikul510 I'm no objective-c developer so I'd really appreciate it if someone could test before I submit a PR.

Mainly I'm hoping the change will fix https://github.com/rt2zz/react-native-contacts/issues/136, and I think it will be faster.

And as a sweetener I think I've also fixed https://github.com/rt2zz/react-native-contacts/issues/121 and https://github.com/rt2zz/react-native-contacts/issues/108 and probably https://github.com/rt2zz/react-native-contacts/issues/86, https://github.com/rt2zz/react-native-contacts/issues/84

**Comment by npomfret** [comment]
Closing as we are now using the new API.
