### ISSUE TITLE
:react-native-contacts:compileReleaseJavaWithJavac fails on build

### ISSUE THREAD

**Issue by asqwrd** [rt2zz/react-native-contacts#88]
When i do react-native run android after installing and setting everything up i get an error 

> node_modules\react-native-contacts\android\src\main\java\com\rt2zz\reactnativecontacts\ContactsProvider.java:149: error: incompatible types: String cannot be converted to int
                contact.photoUri = getPhotoURIFromContactURI(rawPhotoURI, contactId);

not sure what i am missing.  Any help would be appreciated

**Comment by morenoh149** [comment]
can you test if changing `int contactId` to `string contactId` fixes it? https://github.com/rt2zz/react-native-contacts/blob/master/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java#L211

**Comment by fkoester** [comment]
Had the same issue and applying the change mentioned by @morenoh149  fixed it for me.

**Comment by asqwrd** [comment]
Yea that worked for me as well just tested it and it compiles fine now

**Comment by morenoh149** [comment]
fix is on npm now. Thanks for the testing @fkoester @asqwrd .
