### ISSUE TITLE
App crash on contact setting toggled

### ISSUE THREAD

**Issue by morenoh149** [rt2zz/react-native-contacts#9]
When simulating ios and manually toggling the permission to contacts the app crashes. Not sure if this is going to cause issues in a deployed app. Please advise.
![screen shot 2015-11-03 at 11 22 38 am](https://cloud.githubusercontent.com/assets/587438/10913724/470cbade-821d-11e5-93aa-c1210a6683d9.png)
![screen shot 2015-11-03 at 11 22 46 am](https://cloud.githubusercontent.com/assets/587438/10913726/470feab0-821d-11e5-903b-a508bc4c64f0.png)

**Comment by JeanLebrument** [comment]
This is a correct behaviour: http://stackoverflow.com/questions/12522574/toggling-privacy-settings-will-kill-the-app

```
the OS sends a SIGKILL which is not a crash - Apple session on privacy in iOS6 says:

If permissions changes, app is quit.
Background task expiration handler is called, if registered
iOS then kills the application.
```

**Comment by morenoh149** [comment]
okay great.
