### ISSUE TITLE
Duplicate?

### ISSUE THREAD

**Issue by skeie** [rt2zz/react-native-contacts#96]
Hi, I have one contact on my Android Honor phone. So when I use `Contacts.getAll()` I get this:
  {
    emailAddresses: [],
      phoneNumbers: [{ label: 'mobile', number: '1337' }],
        thumbnailPath: '',
          familyName: null,
            middleName: null,
              givenName: 'test',
                recordID: '42470598bf3db8d'
  }
  {
    emailAddresses: [],
      phoneNumbers: [{ label: 'mobile', number: '1337' }],
        thumbnailPath: '',
          familyName: null,
            middleName: null,
              givenName: 'test',
                recordID: '1289'
  }

I think it's because of other apps. Like whatsapp. Do you know if its possible to only get contacts from your sim / gmail?

**Comment by morenoh149** [comment]
I think it'd be much simpler to detect related contacts in application code and merge them yourself. I actually do this in one of my apps. Otherwise the bridge would only return some of the contacts. Sorry.
