### ISSUE TITLE
Shall we remove thumbnailPath from the API?

### ISSUE THREAD

**Issue by npomfret** [rt2zz/react-native-contacts#97]
Hi @rt2zz  @morenoh149 - sorry for the provocative title, just wanted to get a quick discussion going.

I've noticed that some people have very large address books and the creation of thumbnail files appears to be causing performance problems (as well as a total crash in iOS, but that's being fixed).

I want to suggest a change to the API where thumbnails are not returned by default, but have to be asked for explicitly. This would mean the clients who aren't interested in the thumbnails don't suffer from the slow process of all file creation that's required.  Plus a boost for those who do want thumbnails where it would create the thumbnail paths on demand, rather than all at once.  It might be faster and might reduce disk usage.

The api currently returns a `recordID` field for each contact I believe.  We could use that ID in the API, something like

`Contacts.getThumbnailPath(contact.recordID)`

The implementation could check to see if a thumbnail file already exists, create one if it doesn't, and then return it. 

Thoughts?

**Comment by morenoh149** [comment]
sounds good to me. I'd prefer however to do this in a backwards compatible way. This could be with an options object that disables the thumbnail fetching. Say

`Contacts.getAll({thumbnails: false})`

thoughts?

**Comment by npomfret** [comment]
I'd be open to that, but it wouldn't be my first choice.  I actually think the icon file creation is a little damaging, I'd rather the user "opted in" if you see what I mean?  But I don't feel strongly about it.

**Comment by morenoh149** [comment]
It's just an effort to protect code that's already been written given the initial api assumptions. If we feel very strongly the api was wrong we could change it and do a major version bump.

Either path requires adding `.getThumbnailPath(:recordID)` to the api.

If we could get numbers on what contact list size crashes start happening, on what type of hardware and your average user's contact list size, it would be easier to make a decision.

**Comment by npomfret** [comment]
I can't give an average, but the app I'm writing has only been deployed onto a few handsets, maybe 15, and 2 of those have address books have thousands of contacts.  Really big address books are more common than I ever thought.  The crashes aren't my concern though (like I said a fix is in progress).  My concern is the performance.  

I think the default API should be a performant one.  If people see an option to include / exclude thumbnails, with the default being to include, I imagine they won't ever consider excluding - even if they have no use for the thumbnails.

I also think breaking changes are ok, like you said we just bump the major version number and add some explanatory notes to the readme. 

@rt2zz do you have any opinion?

(I'd also like to stream the contacts back one by one instead of building an array, but that's a discussion for a future date)

**Comment by morenoh149** [comment]
I will admit, in my app the initial load time is annoying.

**Comment by npomfret** [comment]
I'm happy to do the android work for this, but am not much good at the iOS stuff. 

@bradbumbalough @bdbergeron @Nopik @rt2zz - would any of you guys be able to write the objective-c function to return a file uri for an icon file in the temp dir, given a contact id?

**Comment by Nopik** [comment]
@npomfret you mean like the current one? what differences to the current code you're looking for?

**Comment by Nopik** [comment]
Ah, sorry, I didnt noticed that this is different issue than we've discussed earlier ;)

My 2 cents:
- asking for thumbnail one by one will involve bridge call, which is slow. And, I suspect that most clients would either like to receive all thumbnails, or none. So, for the completness I'd suggest having something like `.getAllContacts({thumbnails: true/false})` + `.getThumbnailPath()` on a record.
- Currently thumbnails are left forever in tmp directory. If app happen to ask for them many times, many copies of that thumbnail is created. Since app does know the path, it can remove the file. BUT, doing so from javascript level is very inconvenient. So, option to remove the file containing thumbnail should be there, like `.removeThumbnail()` on a record.
- preferably, record should generate the thumbnail once and do not create new file until remove is called, for all of the above reasons.

@npomfret answering your question: yeah, I can write obj-c function like this. Just let me know about the exact API you need. Wont be able to write android counterpart myself, but if you'll need some help my team can help, I think.

**Comment by npomfret** [comment]
Thanks @Nopik

I've had a stab at an implementation, but as I said I really don't know what I'm doing in xCode.  I also hadn't considered your first point about having a chatty interface, do you think this would be unusably slow?  It didn't matter for my app because I don't use all the contacts, but I think you're right in that most apps would.  If so, my implementation isn't at all valid, but I'll explain anyway...

So as a first attempt in my fork I've altered both implementations to not generate the icon files.  Instead I've added a `getIconUri` method which returns a promise.  This method creates the icon file (if it doesn't exist) and returns a file url to it.  Not the file is created with a known filename (using the recordID) in a known direction (currently I chose the _cache_ directory).

The iOS implementation is [here](https://github.com/npomfret/react-native-contacts/blob/9f701f77e0d9e76a7e7c3543f75f9bc60e28d88c/ios/RCTContacts/RCTContacts.m#L62). I didn't understand what the existing `getABPersonThumbnailFilepath` did so I wrote new code to do file creation.  There's an unused parameter in there which was required for the Android implementation (explained below).

The JS code looks like this:

```
          RNContacts.getIconUri(contact.recordID, contact.thumbnailPath)
            .then((icon) => {
              console.log("icon", contact.recordID, icon);
            })
            .catch((err) => {
              console.warn("icon", contact, err);
            });
```

`RNContacts.getIconUri` takes 2 arguments, the 1st is the record id, and the second is for a fast android implementation.  It's the native uri to the icon.  By passing this though we avoid looking up the record in the contacts database.

Perhaps another solution would be to return the icon uris in the same way that we currently do, but we generate the files asynchronously, either automatically (as a side-effect of returning a contact) or explicitly with a method call.  Use the same technique to generate the files using the record id, which would prevent duplicates being created. 

Whether or not to overwrite existing files, or skip file creation if a file exists is a tricky one.  It would be nice as a performance boost to not regenerate files unnecessarily. But if a icon for a contact changes you would want to overwrite it.  

Perhaps the api should be...

`getAll({generateIconFiles: true, overwriteExistingiconFiles: false});`

I feel fairly strongly that the file generation needs to be asynchronous, or at the least there should be an option for it to be asynchronous.

`getAll({generateIconFiles: true, overwriteExistingiconFiles: false, generateIconFilesAsync: true});`

**Comment by mikesurowiec** [comment]
@npomfret we had someone with ~1500 contacts (linked across social), and calling `getAll` would crash it consistently (they were on an iPhone 7). Hard to say how many of those contacts had thumbnail images, but it's a data point to keep in mind

**Comment by npomfret** [comment]
Hmm, another reason to look at this https://github.com/rt2zz/react-native-contacts/issues/106

I've got some time coming up.  I'll see if I can come up with a suitable change to the API

**Comment by npomfret** [comment]
closing as the new api allows for exactly this
